export default {
  backendType: "twilio",
  label: "Twilio",
  description: "Send SMS/MMS/WhatsApp, make & manage voice calls, run Verify OTP, and look up numbers.",
  fields: [
    { name: "credentialId", label: "Account SID & Auth Token", type: "credential", accentColor: "#F22F46" },
    { type: "notice", variant: "info", text: "Store your Twilio credential as AccountSID:AuthToken (colon-separated)." },
    { name: "operation", label: "Operation", type: "options", cols: 3, default: "sendSms", options: [
      { value: "sendSms",          label: "Send SMS" },
      { value: "sendMms",          label: "Send MMS" },
      { value: "sendWhatsApp",     label: "Send WhatsApp" },
      { value: "getMessage",       label: "Get Message" },
      { value: "listMessages",     label: "List Messages" },
      { value: "deleteMessage",    label: "Delete Message" },
      { value: "makeCall",         label: "Make Call" },
      { value: "getCall",          label: "Get Call" },
      { value: "listCalls",        label: "List Calls" },
      { value: "hangupCall",       label: "Hang Up Call" },
      { value: "sendVerification", label: "Send OTP" },
      { value: "checkVerification",label: "Check OTP" },
      { value: "lookupNumber",     label: "Lookup Number" },
      { value: "listNumbers",      label: "List Numbers" },
    ]},

    { name: "to", label: "To", type: "string", smart: true, placeholder: "+15551234567",
      show: { operation: ["sendSms","sendMms","sendWhatsApp","makeCall","sendVerification","checkVerification"] } },
    { name: "from", label: "From (Twilio number)", type: "string", smart: true, placeholder: "+15559876543",
      show: { operation: ["sendSms","sendMms","sendWhatsApp","makeCall"] } },

    { name: "body", label: "Message", type: "string", smart: true, multiline: true,
      show: { operation: ["sendSms","sendWhatsApp"] } },
    { name: "body", label: "Caption (optional)", type: "string", smart: true, multiline: true,
      show: { operation: "sendMms" } },
    { name: "mediaUrl", label: "Media URL", type: "string", smart: true, placeholder: "https://example.com/image.jpg",
      hint: "Publicly reachable https URL of the image/file to attach", show: { operation: ["sendMms","sendWhatsApp"] } },

    { name: "url", label: "TwiML URL", type: "string", smart: true, placeholder: "https://example.com/voice.xml",
      hint: "URL returning TwiML that controls the call flow", show: { operation: "makeCall" } },

    { name: "messageSid", label: "Message SID", type: "string", smart: true, placeholder: "SMxxxxxxxx",
      show: { operation: ["getMessage","deleteMessage"] } },
    { name: "callSid", label: "Call SID", type: "string", smart: true, placeholder: "CAxxxxxxxx",
      show: { operation: ["getCall","hangupCall"] } },

    { name: "to", label: "Filter by To (optional)", type: "string", smart: true, placeholder: "+15551234567",
      show: { operation: ["listMessages","listCalls"] } },
    { name: "from", label: "Filter by From (optional)", type: "string", smart: true, placeholder: "+15559876543",
      show: { operation: ["listMessages","listCalls"] } },
    { name: "status", label: "Filter by Status (optional)", type: "string", smart: true, placeholder: "completed",
      show: { operation: "listCalls" } },
    { name: "maxResults", label: "Max Results", type: "number", default: 20,
      show: { operation: ["listMessages","listCalls","listNumbers"] } },

    { name: "verifyServiceSid", label: "Verify Service SID", type: "string", smart: true, placeholder: "VAxxxxxxxx",
      hint: "From Twilio Verify — the service that owns this OTP flow",
      show: { operation: ["sendVerification","checkVerification"] } },
    { name: "channel", label: "Channel", type: "options", cols: 3, default: "sms",
      options: [{ value: "sms", label: "SMS" }, { value: "call", label: "Call" }, { value: "email", label: "Email" }],
      show: { operation: "sendVerification" } },
    { name: "code", label: "OTP Code", type: "string", smart: true, placeholder: "123456",
      show: { operation: "checkVerification" } },

    { name: "phoneNumber", label: "Phone Number", type: "string", smart: true, placeholder: "+15551234567",
      hint: "E.164 format — returns carrier and line type info", show: { operation: "lookupNumber" } },
  ],
  outputs: ["sid", "status", "messages", "calls", "valid", "carrier", "numbers"],
};
