export default {
  backendType: "teams",
  label: "Microsoft Teams",
  description: "Send messages, cards, create channels, and schedule meetings in Microsoft Teams.",
  fields: [
    { type: "notice", variant: "info", text: "Requires a Microsoft 365 OAuth credential with Teams permissions." },
    { name: "credentialId", label: "Microsoft 365 OAuth", type: "credential", accentColor: "#6264A7" },
    { name: "operation", label: "Operation", type: "options", cols: 3, default: "sendMessage", options: [
      { value: "sendMessage",    label: "Send Message" },
      { value: "sendCard",       label: "Send Card" },
      { value: "replyMessage",   label: "Reply to Message" },
      { value: "createChannel",  label: "Create Channel" },
      { value: "listChannels",   label: "List Channels" },
      { value: "listTeams",      label: "List Teams" },
      { value: "createMeeting",  label: "Create Meeting" },
    ]},
    { name: "teamId", label: "Team ID", type: "string", smart: true, show: { operation: ["sendMessage","sendCard","replyMessage","createChannel","listChannels"] } },
    { name: "channelId", label: "Channel ID", type: "string", smart: true, show: { operation: ["sendMessage","sendCard","replyMessage"] } },
    { name: "message", label: "Message", type: "string", smart: true, multiline: true, show: { operation: "sendMessage" } },
    { name: "cardTitle", label: "Card Title", type: "string", smart: true, show: { operation: "sendCard" } },
    { name: "cardText", label: "Card Text", type: "string", smart: true, multiline: true, show: { operation: "sendCard" } },
    { name: "buttonLabel", label: "Button Label (optional)", type: "string", smart: true, show: { operation: "sendCard" } },
    { name: "buttonUrl", label: "Button URL (optional)", type: "string", smart: true, show: { operation: "sendCard" } },
    { name: "messageId", label: "Message ID", type: "string", smart: true, show: { operation: "replyMessage" } },
    { name: "reply", label: "Reply", type: "string", smart: true, multiline: true, show: { operation: "replyMessage" } },
    { name: "name", label: "Channel Name", type: "string", smart: true, show: { operation: "createChannel" } },
    { name: "description", label: "Description (optional)", type: "string", smart: true, show: { operation: "createChannel" } },
    { name: "isPrivate", label: "Private Channel", type: "boolean", default: false, show: { operation: "createChannel" } },
    { name: "subject", label: "Subject", type: "string", smart: true, show: { operation: "createMeeting" } },
    { name: "startTime", label: "Start Time", type: "string", smart: true, placeholder: "2024-12-25T10:00:00", show: { operation: "createMeeting" } },
    { name: "endTime", label: "End Time", type: "string", smart: true, placeholder: "2024-12-25T11:00:00", show: { operation: "createMeeting" } },
    { name: "attendees", label: "Attendees", type: "string", smart: true, multiline: true, hint: "One email per line", show: { operation: "createMeeting" } },
  ],
  outputs: ["message", "channel", "channels", "teams", "meeting"],
};
