export default {
  backendType: "onedrive",
  label: "OneDrive",
  description: "List, upload, download, move, and share files and folders in Microsoft OneDrive.",
  fields: [
    { name: "credentialId", type: "credential", label: "Microsoft Credential", accentColor: "#0078D4" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "listFiles", options: [
      { value: "listFiles",    label: "List Files" },
      { value: "uploadFile",   label: "Upload File" },
      { value: "downloadFile", label: "Download File" },
      { value: "createFolder", label: "Create Folder" },
      { value: "deleteFile",   label: "Delete File" },
      { value: "moveFile",     label: "Move File" },
      { value: "getFileInfo",  label: "Get File Info" },
      { value: "shareFile",    label: "Share File" },
    ]},
    { name: "folderId", type: "string", label: "Folder ID", smart: true, default: "root",
      hint: "Leave blank for root",
      show: { operation: ["listFiles"] } },
    { name: "limit", type: "number", label: "Limit", default: 100,
      show: { operation: ["listFiles"] } },
    { name: "fileName", type: "string", label: "File Name", smart: true,
      show: { operation: ["uploadFile"] } },
    { name: "content", type: "string", label: "File Content", smart: true, multiline: true,
      show: { operation: ["uploadFile"] } },
    { name: "parentFolderId", type: "string", label: "Parent Folder ID", smart: true, default: "root",
      show: { operation: ["uploadFile","createFolder"] } },
    { name: "itemId", type: "string", label: "Item ID", smart: true, placeholder: "OneDrive item ID",
      show: { operation: ["downloadFile","deleteFile","moveFile","getFileInfo","shareFile"] } },
    { name: "name", type: "string", label: "Folder Name", smart: true,
      show: { operation: ["createFolder"] } },
    { name: "destinationFolderId", type: "string", label: "Destination Folder ID", smart: true,
      show: { operation: ["moveFile"] } },
    { name: "type", type: "options", label: "Permission Type", cols: 2, default: "view",
      options: [
        { value: "view", label: "View" },
        { value: "edit", label: "Edit" },
      ],
      show: { operation: ["shareFile"] } },
    { name: "scope", type: "options", label: "Scope", cols: 2, default: "anonymous",
      options: [
        { value: "anonymous",    label: "Anonymous" },
        { value: "organization", label: "Organization" },
      ],
      show: { operation: ["shareFile"] } },
  ],
  outputs: ["file","files","item","url","folder"],
};
