export default {
  backendType: "sftp",
  label: "SFTP",
  description: "List, upload, download, delete, and rename files on an SFTP server.",
  fields: [
    { name: "credentialId", type: "credential", label: "SFTP Credential", accentColor: "#4A90D9" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "listFiles", options: [
      { value: "listFiles",    label: "List Files" },
      { value: "uploadFile",   label: "Upload File" },
      { value: "downloadFile", label: "Download File" },
      { value: "deleteFile",   label: "Delete File" },
      { value: "makeDirectory", label: "Make Directory" },
      { value: "renameFile",   label: "Rename File" },
    ]},
    { name: "remotePath", type: "string", label: "Remote Path", smart: true, default: "/",
      show: { operation: ["listFiles"] } },
    { name: "localContent", type: "string", label: "File Content", smart: true, multiline: true,
      hint: "File content to upload",
      show: { operation: ["uploadFile"] } },
    { name: "remotePath", type: "string", label: "Remote Path", smart: true, placeholder: "/home/user/file.txt",
      show: { operation: ["uploadFile","downloadFile","deleteFile"] } },
    { name: "remotePath", type: "string", label: "Remote Path", smart: true, placeholder: "/home/user/newdir",
      show: { operation: ["makeDirectory"] } },
    { name: "oldPath", type: "string", label: "Old Path", smart: true,
      show: { operation: ["renameFile"] } },
    { name: "newPath", type: "string", label: "New Path", smart: true,
      show: { operation: ["renameFile"] } },
  ],
  outputs: ["files","content","path","success"],
};
