export default {
  backendType: "sftp",
  label: "SFTP",
  description: "List, upload, download, delete, and rename files on an SFTP server.",
  fields: [
    { name: "credentialId", type: "credential", label: "SFTP Credential", accentColor: "#4A90D9",
      hint: "Holds host, username and password or private key. Fill the fields below instead to connect without a saved credential." },
    { name: "row", type: "row", fields: [
      { name: "host", type: "string", label: "Host", smart: true, placeholder: "sftp.example.com" },
      { name: "port", type: "number", label: "Port", default: 22 },
    ]},
    { name: "username", type: "string", label: "Username", smart: true, placeholder: "deploy" },
    { name: "authType", type: "options", label: "Authenticate With", default: "password", options: [
      { value: "password",   label: "Password" },
      { value: "privateKey", label: "Private Key" },
    ]},
    { name: "password", type: "string", label: "Password", smart: true, show: { authType: "password" } },
    { name: "privateKey", type: "string", label: "Private Key", smart: true, multiline: true,
      placeholder: "-----BEGIN OPENSSH PRIVATE KEY-----",
      show: { authType: "privateKey" } },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "listFiles", options: [
      { value: "listFiles",     label: "List Files", desc: "List the contents of a remote directory" },
      { value: "uploadFile",    label: "Upload File", desc: "Write a file to the remote server" },
      { value: "downloadFile",  label: "Download File", desc: "Read a file from the remote server" },
      { value: "deleteFile",    label: "Delete File", desc: "Permanently remove a remote file" },
      { value: "makeDirectory", label: "Make Directory", desc: "Create a directory on the remote server" },
      { value: "renameFile",    label: "Rename File", desc: "Move or rename a remote file" },
      { value: "copyFile",      label: "Copy File", desc: "Duplicate a remote file to another path" },
      { value: "exists",        label: "File Exists", desc: "Check whether a remote path exists" },
    ]},
    { name: "remotePath", type: "string", label: "Remote Path", smart: true, default: "/",
      placeholder: "/home/user/file.txt",
      hint: "Directory for list and make-directory, otherwise the file itself." },
    { name: "content", type: "string", label: "File Content", smart: true, multiline: true,
      show: { operation: ["uploadFile"] } },
    { name: "destPath", type: "string", label: "Destination Path", smart: true,
      placeholder: "/home/user/renamed.txt",
      show: { operation: ["renameFile","copyFile"] } },
  ],
  outputs: ["files","content","path","success"],
};
