export default {
  backendType: "google_sheets",
  label: "Google Sheets",
  description: "Read, write, append, and manage data in Google Sheets spreadsheets.",
  fields: [
    { name: "credentialId", type: "credential", label: "Google Credential", accentColor: "#34A853" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "readRange", options: [
      { value: "readRange",   label: "Read Range" },
      { value: "writeRange",  label: "Write Range" },
      { value: "appendRow",   label: "Append Row" },
      { value: "clearRange",  label: "Clear Range" },
      { value: "getSheet",    label: "Get Sheet Info" },
      { value: "createSheet", label: "Create Sheet" },
    ]},
    { name: "spreadsheetId", type: "string", label: "Spreadsheet ID", smart: true, placeholder: "1BxiMVs..." },
    { name: "range", type: "string", label: "Range", smart: true, placeholder: "Sheet1!A1:D10",
      show: { operation: ["readRange"] } },
    { name: "majorDimension", type: "options", label: "Major Dimension", cols: 2, default: "ROWS",
      options: [
        { value: "ROWS",    label: "Rows" },
        { value: "COLUMNS", label: "Columns" },
      ],
      show: { operation: ["readRange"] } },
    { name: "range", type: "string", label: "Range", smart: true, placeholder: "Sheet1!A1",
      show: { operation: ["writeRange"] } },
    { name: "values", type: "string", label: "Values", smart: true, multiline: true,
      hint: "JSON 2D array: [[row1col1,row1col2],[row2...]]",
      show: { operation: ["writeRange","appendRow"] } },
    { name: "valueInputOption", type: "options", label: "Input Option", cols: 2, default: "USER_ENTERED",
      options: [
        { value: "RAW",          label: "Raw" },
        { value: "USER_ENTERED", label: "User Entered" },
      ],
      show: { operation: ["writeRange"] } },
    { name: "range", type: "string", label: "Range", smart: true, placeholder: "Sheet1!A:Z",
      show: { operation: ["appendRow"] } },
    { name: "range", type: "string", label: "Range", smart: true, placeholder: "Sheet1!A1:Z100",
      show: { operation: ["clearRange"] } },
    { name: "title", type: "string", label: "Sheet Title", smart: true, placeholder: "New Sheet",
      show: { operation: ["createSheet"] } },
  ],
  outputs: ["values","rows","updatedRange","sheet","spreadsheetId"],
};
