export default {
  backendType: "postgres",
  label: "PostgreSQL",
  description: "Query, insert, update, delete, upsert, and run transactions on a PostgreSQL database.",
  fields: [
    { name: "credentialId", type: "credential", label: "PostgreSQL Credential", accentColor: "#336791" },

    { name: "sql", type: "string", label: "SQL", smart: true, multiline: true, required: true,
      placeholder: "SELECT * FROM users WHERE id = $1",
      hint: "Use $1, $2… placeholders — never concatenate values into the string",
      show: { operation: ["query", "queryOne", "execute"] } },
    { name: "params", type: "string", label: "Parameters", smart: true,
      hint: "JSON array of placeholder values: [1, \"John\"]",
      show: { operation: ["query", "queryOne", "execute", "update", "deleteRows"] } },
    { name: "rowLimit", type: "number", label: "Row Limit", default: 1000,
      show: { operation: ["query"] } },

    { name: "table", type: "string", label: "Table", smart: true, required: true, placeholder: "users",
      show: { operation: ["insert", "update", "deleteRows", "upsert", "tableColumns"] } },
    { name: "values", type: "string", label: "Values", smart: true, multiline: true, required: true,
      hint: "JSON object of column → value: {\"email\": \"a@b.com\", \"plan\": \"pro\"}",
      show: { operation: ["insert", "update", "upsert"] } },
    { name: "where", type: "string", label: "Where Clause", smart: true, required: true,
      placeholder: "id = $1",
      hint: "SQL without the WHERE keyword. Placeholders map to Parameters above.",
      show: { operation: ["update", "deleteRows"] } },
    { name: "conflictColumns", type: "string", label: "Conflict Columns", smart: true, required: true,
      placeholder: "id,email",
      hint: "Comma-separated unique columns that trigger the update",
      show: { operation: ["upsert"] } },

    { name: "statements", type: "string", label: "Statements", smart: true, multiline: true, required: true,
      hint: "JSON array of {sql, params} objects. Transaction rolls all back if any one fails.",
      show: { operation: ["batch", "transaction"] } },

    { name: "schema", type: "string", label: "Schema", smart: false, default: "public",
      show: { operation: ["listTables", "tableColumns"] } },
  ],
  outputs: ["rows", "row", "rowCount", "command", "tables", "columns"],
};
