export default {
  backendType: "postgres",
  label: "PostgreSQL",
  description: "Query, insert, update, delete, upsert, and run transactions on a PostgreSQL database.",
  fields: [
    { name: "credentialId", type: "credential", label: "PostgreSQL Credential", accentColor: "#336791" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "query", options: [
      { value: "query",       label: "Query" },
      { value: "insert",      label: "Insert" },
      { value: "update",      label: "Update" },
      { value: "delete",      label: "Delete" },
      { value: "upsert",      label: "Upsert" },
      { value: "transaction", label: "Transaction" },
    ]},
    { name: "sql", type: "string", label: "SQL", smart: true, multiline: true,
      placeholder: "SELECT * FROM users WHERE id = $1",
      hint: "Use $1, $2... for parameters",
      show: { operation: ["query"] } },
    { name: "params", type: "string", label: "Parameters", smart: true,
      hint: "JSON array of parameter values: [1, 'John']",
      show: { operation: ["query"] } },
    { name: "table", type: "string", label: "Table", smart: true, placeholder: "users",
      show: { operation: ["insert","update","delete","upsert"] } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true,
      hint: "JSON object or array of objects",
      show: { operation: ["insert"] } },
    { name: "filter", type: "string", label: "Filter", smart: true, multiline: true,
      hint: "JSON object: {id: 1}",
      show: { operation: ["update","delete"] } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true,
      hint: "JSON object of columns to update",
      show: { operation: ["update"] } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true,
      hint: "JSON object",
      show: { operation: ["upsert"] } },
    { name: "conflictColumns", type: "string", label: "Conflict Columns", smart: true,
      hint: "Comma-separated: id,email",
      show: { operation: ["upsert"] } },
    { name: "queries", type: "string", label: "Queries", smart: true, multiline: true,
      hint: "JSON array of {sql, params} objects",
      show: { operation: ["transaction"] } },
  ],
  outputs: ["rows","rowCount","insertedId","row"],
};
