export default {
  backendType: "google_calendar",
  label: "Google Calendar",
  description: "List, create, update, delete events and manage Google Calendar calendars.",
  fields: [
    { name: "credentialId", type: "credential", label: "Google Credential", accentColor: "#4285F4" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "listEvents", options: [
      { value: "listEvents",    label: "List Events" },
      { value: "createEvent",   label: "Create Event" },
      { value: "getEvent",      label: "Get Event" },
      { value: "updateEvent",   label: "Update Event" },
      { value: "deleteEvent",   label: "Delete Event" },
      { value: "listCalendars", label: "List Calendars" },
    ]},
    { name: "calendarId", type: "string", label: "Calendar ID", smart: true, default: "primary",
      hint: "Use 'primary' for main calendar" },
    { name: "timeMin", type: "string", label: "Time Min", smart: true, placeholder: "ISO datetime",
      show: { operation: ["listEvents"] } },
    { name: "timeMax", type: "string", label: "Time Max", smart: true,
      show: { operation: ["listEvents"] } },
    { name: "maxResults", type: "number", label: "Max Results", default: 10,
      show: { operation: ["listEvents"] } },
    { name: "q", type: "string", label: "Search Term", smart: true, placeholder: "Search term",
      show: { operation: ["listEvents"] } },
    { name: "summary", type: "string", label: "Summary", smart: true,
      show: { operation: ["createEvent"] } },
    { name: "description", type: "string", label: "Description", smart: true, multiline: true,
      show: { operation: ["createEvent"] } },
    { name: "start", type: "string", label: "Start", smart: true, placeholder: "2024-12-25T10:00:00",
      show: { operation: ["createEvent"] } },
    { name: "end", type: "string", label: "End", smart: true, placeholder: "2024-12-25T11:00:00",
      show: { operation: ["createEvent"] } },
    { name: "timezone", type: "string", label: "Timezone", smart: true, default: "UTC",
      show: { operation: ["createEvent"] } },
    { name: "attendees", type: "string", label: "Attendees", smart: true, multiline: true,
      hint: "One email per line",
      show: { operation: ["createEvent"] } },
    { name: "location", type: "string", label: "Location", smart: true,
      show: { operation: ["createEvent"] } },
    { name: "eventId", type: "string", label: "Event ID", smart: true,
      show: { operation: ["getEvent","updateEvent","deleteEvent"] } },
    { name: "summary", type: "string", label: "Summary", smart: true,
      show: { operation: ["updateEvent"] } },
    { name: "description", type: "string", label: "Description", smart: true, multiline: true,
      show: { operation: ["updateEvent"] } },
    { name: "start", type: "string", label: "Start", smart: true,
      show: { operation: ["updateEvent"] } },
    { name: "end", type: "string", label: "End", smart: true,
      show: { operation: ["updateEvent"] } },
  ],
  outputs: ["events","event","calendars","eventId"],
};
