export {
  screenshot,
  openUrl,
  leftClick,
  rightClick,
  doubleClick,
  mouseMove,
  typeText,
  pressKey,
  scroll,
  runCommand,
  closeSession,
  sessionInfo,
  dispatchAction,
} from "../nodes/VirtualComputer.js";
