export default {
  backendType: "google_forms",
  label: "Google Forms",
  description: "Get forms, list forms, retrieve responses, and create new Google Forms.",
  fields: [
    { name: "credentialId", type: "credential", label: "Google Credential", accentColor: "#7248B9" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "getForm", options: [
      { value: "getForm",      label: "Get Form" },
      { value: "listForms",    label: "List Forms" },
      { value: "getResponses", label: "Get Responses" },
      { value: "createForm",   label: "Create Form" },
    ]},
    { name: "formId", type: "string", label: "Form ID", smart: true,
      show: { operation: ["getForm","getResponses"] } },
    { name: "pageSize", type: "number", label: "Page Size", default: 20,
      show: { operation: ["listForms"] } },
    { name: "pageSize", type: "number", label: "Page Size", default: 50,
      show: { operation: ["getResponses"] } },
    { name: "filter", type: "string", label: "Filter", smart: true,
      show: { operation: ["getResponses"] } },
    { name: "title", type: "string", label: "Title", smart: true,
      show: { operation: ["createForm"] } },
    { name: "description", type: "string", label: "Description", smart: true,
      show: { operation: ["createForm"] } },
    { name: "items", type: "string", label: "Items", smart: true, multiline: true,
      hint: "JSON array of form items",
      show: { operation: ["createForm"] } },
  ],
  outputs: ["form","forms","responses","formId"],
};
