export default {
  backendType: "sendgrid",
  label: "SendGrid",
  description: "Send transactional emails, use dynamic templates, send bulk campaigns, and manage contacts via SendGrid.",
  fields: [
    { name: "credentialId", label: "API Key", type: "credential", accentColor: "#1A82E2" },
    { name: "operation", label: "Operation", type: "options", cols: 2, default: "sendEmail", options: [
      { value: "sendEmail",    label: "Send Email" },
      { value: "sendTemplate", label: "Send Template" },
      { value: "sendBulk",     label: "Send Bulk" },
      { value: "addContact",   label: "Add Contact" },
    ]},
    { name: "to", label: "To", type: "string", smart: true, show: { operation: ["sendEmail","sendTemplate"] } },
    { name: "from", label: "From", type: "string", smart: true, show: { operation: ["sendEmail","sendTemplate","sendBulk"] } },
    { name: "subject", label: "Subject", type: "string", smart: true, show: { operation: "sendEmail" } },
    { name: "html", label: "HTML Body", type: "string", smart: true, multiline: true, show: { operation: "sendEmail" } },
    { name: "text", label: "Plain Text Body (optional)", type: "string", smart: true, multiline: true, show: { operation: "sendEmail" } },
    { name: "templateId", label: "Template ID", type: "string", smart: true, show: { operation: "sendTemplate" } },
    { name: "dynamicData", label: "Template Data", type: "string", smart: true, multiline: true, hint: "JSON object with template variables", show: { operation: "sendTemplate" } },
    { name: "recipients", label: "Recipients", type: "string", smart: true, multiline: true, hint: 'JSON array of {to, subject, html} objects', show: { operation: "sendBulk" } },
    { name: "email", label: "Email", type: "string", smart: true, show: { operation: "addContact" } },
    { name: "firstName", label: "First Name (optional)", type: "string", smart: true, show: { operation: "addContact" } },
    { name: "lastName", label: "Last Name (optional)", type: "string", smart: true, show: { operation: "addContact" } },
    { name: "listIds", label: "List IDs (optional)", type: "string", smart: true, hint: "Comma-separated SendGrid list IDs", show: { operation: "addContact" } },
  ],
  outputs: ["result", "jobId"],
};
