// Per-node action list — shown in AddNodeSidebar two-step picker
// Each entry: { name, description }

export const NODE_ACTIONS = {
  // ── AI Models ───────────────────────────────────────────────────────────────
  openai: [
    { name: "Chat Completion", description: "Send a prompt and get a text response from GPT" },
    { name: "Stream Chat", description: "Stream tokens in real-time for faster perceived response" },
    { name: "Generate Image", description: "Create images with DALL·E 3 from a text prompt" },
    { name: "Transcribe Audio", description: "Convert audio or video to text using Whisper" },
    { name: "Create Embedding", description: "Generate a vector embedding for text content" },
    { name: "Moderate Content", description: "Check text for policy violations using the moderation API" },
    { name: "Text to Speech", description: "Convert text to natural-sounding audio with TTS-1" },
    { name: "Vision Analysis", description: "Analyze images and answer questions about them" },
    { name: "Function Calling", description: "Let GPT call your custom functions to fetch data" },
    { name: "Fine-tune Model", description: "Start a fine-tuning job on a custom dataset" },
  ],
  anthropic: [
    { name: "Chat Completion", description: "Send a prompt and get a response from Claude" },
    { name: "Stream Chat", description: "Stream Claude's response token by token" },
    { name: "Vision Analysis", description: "Upload images and ask Claude questions about them" },
    { name: "Tool Use", description: "Let Claude call your functions to retrieve live data" },
    { name: "Summarize Document", description: "Compress a long document into key points" },
    { name: "Extract Structured Data", description: "Pull named fields from unstructured text" },
    { name: "Code Review", description: "Analyze code and suggest improvements or find bugs" },
    { name: "Multi-turn Conversation", description: "Maintain dialogue context across messages" },
  ],
  gemini: [
    { name: "Chat Completion", description: "Send a prompt and get a response from Gemini" },
    { name: "Stream Chat", description: "Stream Gemini's response in real-time" },
    { name: "Vision Analysis", description: "Analyze images, PDFs, or video frames" },
    { name: "Code Generation", description: "Generate, explain, or debug code" },
    { name: "Audio Transcription", description: "Convert audio to text using Gemini" },
    { name: "Document Summarization", description: "Summarize large documents or PDFs" },
    { name: "Grounded Search", description: "Answer with citations from Google Search" },
    { name: "Create Embedding", description: "Generate semantic vector embeddings" },
  ],
  perplexity: [
    { name: "Search-augmented Chat", description: "Answer questions with live web search results" },
    { name: "Research Deep Dive", description: "Get detailed research with cited sources" },
    { name: "Real-time News", description: "Fetch current events and breaking news" },
    { name: "Citation Summary", description: "Summarize a topic and return source links" },
    { name: "Fact Check", description: "Verify claims against current web sources" },
    { name: "Code Help", description: "Get coding help with Sonar models" },
  ],
  xai: [
    { name: "Chat Completion", description: "Query Grok for a conversational response" },
    { name: "Real-time Knowledge", description: "Get answers using Grok's up-to-date knowledge" },
    { name: "Humor & Sarcasm Mode", description: "Use Grok's uncensored fun tone for creative content" },
    { name: "Code Generation", description: "Generate or explain code with Grok" },
    { name: "Document Analysis", description: "Upload files and ask Grok to analyze them" },
  ],
  deepseek: [
    { name: "Chat Completion", description: "Query DeepSeek for a conversational response" },
    { name: "Code Generation", description: "Generate, explain, or fix code with DeepSeek-Coder" },
    { name: "Math Reasoning", description: "Solve math problems step-by-step" },
    { name: "Document Q&A", description: "Ask questions about a document or text blob" },
    { name: "Stream Chat", description: "Stream DeepSeek's response token by token" },
  ],

  // ── AI Agent Building Blocks ────────────────────────────────────────────────
  ai_agent: [
    { name: "Run Agent Loop", description: "Execute the full ReAct agent loop with tools" },
    { name: "Single Tool Call", description: "Call one specific tool and return its result" },
    { name: "Plan & Execute", description: "Agent plans steps, then executes them sequentially" },
    { name: "Reflection Step", description: "Agent reflects on previous output and self-corrects" },
    { name: "Summarize Memory", description: "Compress long conversation history into a summary" },
  ],
  agent_llm: [
    { name: "Send Message", description: "Send a message to the configured LLM" },
    { name: "Stream Response", description: "Stream tokens for low-latency output" },
    { name: "System Prompt Override", description: "Inject a custom system prompt at runtime" },
  ],
  agent_memory: [
    { name: "Store Memory", description: "Save a key-value pair to agent memory" },
    { name: "Retrieve Memory", description: "Load stored context by key" },
    { name: "Semantic Search", description: "Find the most similar past memories by vector" },
    { name: "Clear Memory", description: "Wipe all stored memory for this session" },
    { name: "List All Memories", description: "Return all stored memory entries" },
  ],
  agent_tool: [
    { name: "Execute Tool", description: "Run a registered tool with the given inputs" },
    { name: "List Available Tools", description: "Return all tools the agent can call" },
    { name: "Validate Tool Input", description: "Check inputs before calling a tool" },
  ],
  agent_memory_window: [
    { name: "Append Message", description: "Add a message to the sliding window buffer" },
    { name: "Get Window", description: "Return the last N messages as context" },
    { name: "Clear Window", description: "Reset the sliding window buffer" },
  ],
  agent_memory_redis: [
    { name: "Store Memory", description: "Save a conversation snapshot to Redis" },
    { name: "Load Memory", description: "Retrieve conversation context from Redis" },
    { name: "TTL Expire", description: "Set time-to-live for memory expiration" },
    { name: "Delete Memory", description: "Remove a memory key from Redis" },
  ],
  agent_memory_mongodb: [
    { name: "Store Memory", description: "Persist conversation memory in MongoDB" },
    { name: "Load Memory", description: "Fetch conversation history from MongoDB" },
    { name: "Search Memory", description: "Query past interactions by metadata" },
    { name: "Delete Memory", description: "Remove a memory document from MongoDB" },
  ],
  agent_memory_postgres: [
    { name: "Store Memory", description: "Write conversation memory to Postgres" },
    { name: "Load Memory", description: "Read conversation history from Postgres" },
    { name: "Search Memory", description: "Query memory by semantic similarity" },
    { name: "Delete Memory", description: "Remove memory records from Postgres" },
  ],
  agent_memory_pinecone: [
    { name: "Upsert Memory", description: "Store a vector embedding in Pinecone" },
    { name: "Semantic Search", description: "Find the most relevant past memories" },
    { name: "Delete Memory", description: "Remove vectors from Pinecone by ID" },
    { name: "Fetch by ID", description: "Retrieve a specific memory vector by its ID" },
  ],
  agent_memory_supabase: [
    { name: "Store Memory", description: "Persist memory in Supabase with pgvector" },
    { name: "Semantic Search", description: "Vector similarity search over stored memories" },
    { name: "Delete Memory", description: "Remove a memory record from Supabase" },
  ],
  agent_memory_zep: [
    { name: "Add Memory", description: "Push new messages into the Zep memory store" },
    { name: "Get Memory", description: "Retrieve summarized session memory from Zep" },
    { name: "Search Memory", description: "Semantic search over Zep memory entries" },
    { name: "Delete Session", description: "Clear all memory for a given session ID" },
  ],

  // ── AI Utilities ─────────────────────────────────────────────────────────────
  ai_classify: [
    { name: "Classify Text", description: "Route text into one of your defined categories" },
    { name: "Multi-label Classification", description: "Assign multiple categories to a single input" },
    { name: "Sentiment Analysis", description: "Detect positive, negative, or neutral tone" },
    { name: "Intent Detection", description: "Identify user intent from a message" },
    { name: "Topic Tagging", description: "Auto-tag content with relevant topics" },
  ],
  ai_extract: [
    { name: "Extract Named Entities", description: "Pull out people, companies, dates, and places" },
    { name: "Extract JSON Schema", description: "Fill a typed schema from unstructured text" },
    { name: "Extract Contact Info", description: "Pull emails, phone numbers, and addresses" },
    { name: "Extract Key Facts", description: "Identify the most important sentences" },
    { name: "Extract Table Data", description: "Convert a text table to structured rows" },
  ],
  ai_transform: [
    { name: "Rewrite Tone", description: "Change the tone — formal, casual, or persuasive" },
    { name: "Expand Content", description: "Elaborate a short blurb into full paragraphs" },
    { name: "Condense Content", description: "Reduce verbose text to its essence" },
    { name: "Translate Language", description: "Convert text to another language" },
    { name: "Fix Grammar", description: "Correct grammar, spelling, and punctuation" },
    { name: "SEO Optimize", description: "Rewrite for search engine ranking" },
  ],

  // ── Data & APIs ──────────────────────────────────────────────────────────────
  http_request: [
    { name: "GET Request", description: "Fetch data from any REST API endpoint" },
    { name: "POST Request", description: "Send JSON body to a REST API" },
    { name: "PUT / PATCH", description: "Update a resource via PUT or PATCH" },
    { name: "DELETE Request", description: "Remove a resource via DELETE" },
    { name: "Upload File (multipart)", description: "Upload a file as multipart form data" },
    { name: "Download File", description: "Download binary content from a URL" },
    { name: "Authenticated Request", description: "Make a request with OAuth, API key, or Basic Auth" },
    { name: "Paginated Fetch", description: "Auto-iterate through paginated API responses" },
  ],
  postgres: [
    { name: "Execute Query", description: "Run a raw SQL SELECT, INSERT, UPDATE, or DELETE" },
    { name: "Insert Row", description: "Insert a single record into a table" },
    { name: "Insert Many Rows", description: "Bulk-insert an array of records" },
    { name: "Update Row", description: "Update records matching a WHERE clause" },
    { name: "Delete Row", description: "Delete records matching a WHERE clause" },
    { name: "Find Row", description: "Fetch a single row by primary key" },
    { name: "List Rows", description: "Fetch multiple rows with optional filters" },
    { name: "Execute Transaction", description: "Run multiple SQL statements atomically" },
  ],
  supabase: [
    { name: "Select Rows", description: "Query a Supabase table with filters" },
    { name: "Insert Row", description: "Insert a new record into a Supabase table" },
    { name: "Update Row", description: "Update matching records in Supabase" },
    { name: "Delete Row", description: "Delete records from a Supabase table" },
    { name: "Upsert Row", description: "Insert or update a record by primary key" },
    { name: "Call RPC Function", description: "Execute a custom Supabase Postgres function" },
    { name: "Subscribe to Realtime", description: "Listen for live row changes via Supabase Realtime" },
    { name: "Upload Storage File", description: "Upload a file to Supabase Storage bucket" },
  ],
  mongodb: [
    { name: "Find Documents", description: "Query documents with a MongoDB filter" },
    { name: "Find One", description: "Fetch the first matching document" },
    { name: "Insert Document", description: "Insert a single document into a collection" },
    { name: "Insert Many", description: "Bulk-insert multiple documents" },
    { name: "Update Document", description: "Update one document matching a filter" },
    { name: "Delete Document", description: "Remove documents matching a filter" },
    { name: "Aggregate Pipeline", description: "Run a MongoDB aggregation pipeline" },
    { name: "Count Documents", description: "Count documents matching a filter" },
  ],
  redis_node: [
    { name: "Get Value", description: "Retrieve a value from Redis by key" },
    { name: "Set Value", description: "Store a key-value pair with optional TTL" },
    { name: "Delete Key", description: "Remove a key from Redis" },
    { name: "Increment Counter", description: "Atomically increment a numeric value" },
    { name: "Push to List", description: "Append a value to a Redis list" },
    { name: "Pop from List", description: "Remove and return the first item from a list" },
    { name: "Set Hash Field", description: "Set a field in a Redis hash" },
    { name: "Publish Message", description: "Publish to a Redis pub/sub channel" },
  ],
  firebase: [
    { name: "Read Document", description: "Fetch a Firestore document by path" },
    { name: "Write Document", description: "Create or overwrite a Firestore document" },
    { name: "Update Document", description: "Merge fields into an existing Firestore document" },
    { name: "Delete Document", description: "Remove a Firestore document" },
    { name: "Query Collection", description: "Query a Firestore collection with filters" },
    { name: "Push Notification", description: "Send an FCM push notification to a device" },
    { name: "Read Realtime DB", description: "Read from Firebase Realtime Database" },
    { name: "Write Realtime DB", description: "Write to Firebase Realtime Database" },
  ],

  // ── Data Processing ──────────────────────────────────────────────────────────
  filter_array: [
    { name: "Filter by Condition", description: "Keep only items matching a condition" },
    { name: "Remove Nulls", description: "Filter out null, undefined, or empty values" },
    { name: "Filter by Key Exists", description: "Keep items that have a specific field" },
    { name: "Filter by Date Range", description: "Keep items where a date field is in range" },
    { name: "Deduplicate by Field", description: "Remove duplicates based on a field value" },
  ],
  sort_array: [
    { name: "Sort Ascending", description: "Sort items by a field from low to high" },
    { name: "Sort Descending", description: "Sort items by a field from high to low" },
    { name: "Sort by Date", description: "Sort items chronologically by a date field" },
    { name: "Alphabetical Sort", description: "Sort strings alphabetically" },
    { name: "Custom Sort", description: "Sort with a custom comparator expression" },
  ],
  deduplicate: [
    { name: "Deduplicate by Field", description: "Remove duplicate items based on a key field" },
    { name: "Deduplicate Entire Object", description: "Remove fully identical objects from an array" },
    { name: "Keep First Occurrence", description: "When duplicates exist, keep only the first" },
    { name: "Keep Last Occurrence", description: "When duplicates exist, keep only the last" },
  ],
  batch_split: [
    { name: "Split into Batches", description: "Divide an array into N-item chunks" },
    { name: "Process in Parallel", description: "Run batches concurrently for speed" },
    { name: "Sequential Batches", description: "Process batches one at a time in order" },
  ],
  csv_parser: [
    { name: "Parse CSV String", description: "Convert a CSV text into an array of objects" },
    { name: "CSV to JSON", description: "Transform CSV data into JSON format" },
    { name: "JSON to CSV", description: "Convert an array of objects to CSV text" },
    { name: "Read CSV File", description: "Parse a CSV file from a URL or base64 blob" },
    { name: "Map Columns", description: "Rename or reorder CSV columns" },
  ],
  date_time: [
    { name: "Format Date", description: "Convert a date to a specific display format" },
    { name: "Parse Date String", description: "Convert a date string to a Unix timestamp" },
    { name: "Add/Subtract Time", description: "Add or subtract days, hours, or minutes" },
    { name: "Get Current Timestamp", description: "Return the current date and time" },
    { name: "Calculate Difference", description: "Find the difference between two dates" },
    { name: "Convert Timezone", description: "Convert a timestamp from one timezone to another" },
  ],
  crypto_utils: [
    { name: "Hash Data (SHA-256)", description: "Compute the SHA-256 hash of a string" },
    { name: "HMAC Sign", description: "Sign data with a secret key using HMAC" },
    { name: "Encrypt (AES)", description: "Encrypt data using AES symmetric encryption" },
    { name: "Decrypt (AES)", description: "Decrypt AES-encrypted data" },
    { name: "Base64 Encode", description: "Encode binary or text data as base64" },
    { name: "Base64 Decode", description: "Decode a base64 string to raw text" },
    { name: "Generate UUID", description: "Generate a random UUID v4" },
  ],
  data_mapper: [
    { name: "Map Fields", description: "Remap keys in an object to new field names" },
    { name: "Pick Fields", description: "Keep only specified fields from an object" },
    { name: "Omit Fields", description: "Remove specified fields from an object" },
    { name: "Flatten Nested Object", description: "Collapse nested keys into dot-notation" },
    { name: "Merge Objects", description: "Merge two or more objects into one" },
  ],
  set_fields: [
    { name: "Set Field Value", description: "Add or overwrite a field in the payload" },
    { name: "Set Multiple Fields", description: "Add several key-value pairs at once" },
    { name: "Delete Field", description: "Remove a specific key from the payload" },
    { name: "Rename Field", description: "Rename a key while preserving its value" },
    { name: "Compute Expression", description: "Set a field to a computed expression result" },
  ],

  // ── Research ──────────────────────────────────────────────────────────────────
  web_scraper: [
    { name: "Scrape Page Content", description: "Extract full text content from a URL" },
    { name: "Extract Links", description: "Pull all anchor links from a page" },
    { name: "Scrape Table", description: "Extract HTML table data as structured rows" },
    { name: "Screenshot Page", description: "Capture a screenshot of the rendered page" },
    { name: "Fill & Submit Form", description: "Automate form submission on a webpage" },
    { name: "Wait for Element", description: "Wait for a CSS selector before extracting" },
    { name: "Scrape Multiple Pages", description: "Batch scrape an array of URLs" },
  ],
  web_search: [
    { name: "Web Search", description: "Search the web and return top results" },
    { name: "Image Search", description: "Search for images matching a query" },
    { name: "News Search", description: "Find recent news articles on a topic" },
    { name: "Site-specific Search", description: "Search within a specific domain" },
  ],
  pubmed_search: [
    { name: "Search Articles", description: "Find medical research papers on PubMed" },
    { name: "Fetch Abstract", description: "Retrieve the abstract for a specific PMID" },
    { name: "Find by Author", description: "Search articles by author name" },
    { name: "MeSH Term Search", description: "Search using medical subject headings" },
  ],
  arxiv_search: [
    { name: "Search Papers", description: "Find research papers on arXiv by keyword" },
    { name: "Fetch Paper Details", description: "Get full metadata for an arXiv paper" },
    { name: "Search by Author", description: "Find papers by a specific author" },
    { name: "Recent Papers", description: "Get papers published in the last N days" },
  ],
  wikipedia_lookup: [
    { name: "Search Wikipedia", description: "Find Wikipedia articles matching a query" },
    { name: "Get Article Summary", description: "Fetch the intro section of a Wikipedia page" },
    { name: "Get Full Article", description: "Retrieve the complete Wikipedia article text" },
    { name: "Get Infobox Data", description: "Extract structured data from the article infobox" },
  ],
  drug_lookup: [
    { name: "Lookup Drug Info", description: "Get drug details from FDA database" },
    { name: "Drug Interactions", description: "Check interactions between two drugs" },
    { name: "Dosage Info", description: "Retrieve recommended dosage guidelines" },
    { name: "Generic vs Brand Name", description: "Find generic equivalents for brand-name drugs" },
  ],
  clinical_trials: [
    { name: "Search Trials", description: "Find clinical trials by condition or drug" },
    { name: "Get Trial Details", description: "Fetch full details for a specific trial NCT ID" },
    { name: "Filter by Phase", description: "Find trials in a specific phase (I, II, III)" },
    { name: "Recruiting Trials Only", description: "Show only currently recruiting trials" },
  ],
  weather: [
    { name: "Current Weather", description: "Get real-time weather for a city or coordinates" },
    { name: "5-day Forecast", description: "Fetch the upcoming 5-day weather forecast" },
    { name: "Hourly Forecast", description: "Get weather broken down by hour" },
    { name: "Historical Weather", description: "Fetch past weather data for a date range" },
    { name: "Air Quality Index", description: "Get the AQI and pollutant levels for a location" },
  ],
  news_search: [
    { name: "Search News", description: "Find recent news articles by keyword" },
    { name: "Top Headlines", description: "Get today's top headlines by country or category" },
    { name: "Search by Source", description: "Filter news from specific outlets" },
    { name: "Trending Topics", description: "Get currently trending news topics" },
  ],
  stock_price: [
    { name: "Get Current Price", description: "Fetch the live stock price for a ticker" },
    { name: "Get OHLCV Data", description: "Retrieve open, high, low, close, volume data" },
    { name: "Historical Prices", description: "Fetch price history for a date range" },
    { name: "Company Overview", description: "Get company metadata and fundamentals" },
    { name: "Search Ticker", description: "Find a company's ticker symbol by name" },
  ],
  ip_lookup: [
    { name: "Lookup IP Info", description: "Get country, city, ISP, and org for an IP" },
    { name: "Check IP Reputation", description: "Flag known malicious or VPN IPs" },
    { name: "Reverse DNS Lookup", description: "Resolve hostname from IP address" },
    { name: "Get My IP", description: "Return the outbound IP of this workflow" },
  ],

  // ── Flow Control ─────────────────────────────────────────────────────────────
  condition: [
    { name: "IF / ELSE Branch", description: "Route workflow to true or false branch" },
    { name: "Multiple Conditions (AND)", description: "Only go true if all conditions pass" },
    { name: "Any Condition (OR)", description: "Go true if at least one condition passes" },
    { name: "Value Comparison", description: "Compare a field against a static value" },
    { name: "Regex Match", description: "Branch based on a regex pattern test" },
  ],
  distributor: [
    { name: "Round Robin", description: "Distribute items evenly across all output branches" },
    { name: "Weighted Split", description: "Route a percentage of items to each branch" },
    { name: "First Match Wins", description: "Send to the first branch whose condition matches" },
    { name: "Broadcast to All", description: "Send the same item to every output branch" },
  ],
  logic_router: [
    { name: "Switch on Value", description: "Route to the matching case branch" },
    { name: "Default Fallthrough", description: "Catch unmatched cases in the default branch" },
    { name: "Range-based Routing", description: "Route based on numeric ranges" },
  ],
  delay: [
    { name: "Wait N Seconds", description: "Pause execution for a fixed number of seconds" },
    { name: "Wait Until Time", description: "Pause until a specific datetime" },
    { name: "Random Delay", description: "Add a random delay between a min and max range" },
  ],
  loop: [
    { name: "Loop Over Array", description: "Iterate over each item in an array" },
    { name: "Loop N Times", description: "Repeat a fixed number of times" },
    { name: "While Condition", description: "Repeat while a condition is true" },
    { name: "For Each Batch", description: "Process items in chunks with a loop" },
  ],
  merge: [
    { name: "Merge All Branches", description: "Wait for all branches and combine their outputs" },
    { name: "First Wins", description: "Continue with whichever branch completes first" },
    { name: "Concatenate Arrays", description: "Merge multiple arrays into one flat array" },
    { name: "Deep Merge Objects", description: "Deep-merge two or more objects together" },
  ],
  approval: [
    { name: "Wait for Human Approval", description: "Pause and send an approval request email" },
    { name: "Require Comment", description: "Pause until a reviewer leaves a comment" },
    { name: "Time-out Auto-approve", description: "Auto-approve if no response within N minutes" },
    { name: "Multi-step Approval", description: "Route through a chain of approvers" },
  ],
  wait_for_event: [
    { name: "Wait for Webhook", description: "Pause until a specific webhook fires" },
    { name: "Wait for File", description: "Resume when a file appears in a folder" },
    { name: "Wait for DB Change", description: "Resume when a database value changes" },
  ],
  retry: [
    { name: "Retry on Failure", description: "Retry the previous node up to N times on error" },
    { name: "Exponential Backoff", description: "Retry with increasing delay between attempts" },
    { name: "Retry on Status Code", description: "Only retry on specific HTTP status codes" },
  ],
  stop_error: [
    { name: "Stop with Error", description: "Throw a custom error and halt execution" },
    { name: "Stop Silently", description: "Stop execution without raising an error" },
    { name: "Stop with Warning", description: "Log a warning and stop the current branch" },
  ],
  rate_limiter: [
    { name: "Throttle Requests", description: "Limit API calls to N per second or minute" },
    { name: "Queue Overflow", description: "Queue excess requests instead of dropping them" },
    { name: "Per-user Rate Limit", description: "Apply separate limits per user or tenant" },
  ],
  success_failed: [
    { name: "Route on Success", description: "Continue only if the previous node succeeded" },
    { name: "Route on Failure", description: "Continue only if the previous node failed" },
    { name: "Route on Both", description: "Handle both success and failure paths" },
  ],

  // ── Code ─────────────────────────────────────────────────────────────────────
  code: [
    { name: "Run JavaScript", description: "Execute a JavaScript snippet with access to $input" },
    { name: "Run Python", description: "Execute a Python script with access to workflow data" },
    { name: "Transform Data", description: "Apply a custom transformation to the payload" },
    { name: "Parse & Return", description: "Parse input and return a cleaned-up object" },
    { name: "Validate Schema", description: "Check that data matches a JSON schema" },
    { name: "Custom Logic", description: "Write any custom business logic in code" },
  ],
  variable_set_get: [
    { name: "Set Variable", description: "Store a value in a named workflow variable" },
    { name: "Get Variable", description: "Retrieve a named variable's current value" },
    { name: "Increment Variable", description: "Add to a numeric variable" },
    { name: "Reset Variable", description: "Reset a variable to its initial value" },
  ],
  counter: [
    { name: "Increment", description: "Add 1 (or N) to the counter" },
    { name: "Decrement", description: "Subtract 1 (or N) from the counter" },
    { name: "Reset", description: "Reset the counter to zero" },
    { name: "Get Value", description: "Return the current counter value without changing it" },
  ],
  random_pick: [
    { name: "Pick Random Item", description: "Choose a random element from an array" },
    { name: "Pick N Random Items", description: "Select N random items without replacement" },
    { name: "Shuffle Array", description: "Randomize the order of an array" },
    { name: "Random Number", description: "Generate a random number in a range" },
  ],
  math_expression: [
    { name: "Evaluate Expression", description: "Calculate a math formula with variables" },
    { name: "Round Number", description: "Round to a specific number of decimal places" },
    { name: "Min / Max", description: "Find the minimum or maximum in an array of numbers" },
    { name: "Statistical Summary", description: "Calculate mean, median, and standard deviation" },
  ],
  unit_converter: [
    { name: "Convert Length", description: "Convert meters, feet, miles, km, etc." },
    { name: "Convert Weight", description: "Convert kg, lbs, oz, grams, etc." },
    { name: "Convert Temperature", description: "Convert between Celsius, Fahrenheit, Kelvin" },
    { name: "Convert Currency", description: "Convert between currencies at live rates" },
    { name: "Convert Data Size", description: "Convert bytes, KB, MB, GB, TB" },
  ],

  // ── Messaging & Communication ─────────────────────────────────────────────────
  telegram: [
    { name: "Send Message", description: "Send a text message to a Telegram chat or channel" },
    { name: "Send Photo", description: "Upload and send an image to a Telegram chat" },
    { name: "Send File", description: "Upload and send a document or file" },
    { name: "Edit Message", description: "Edit the text of a previously sent message" },
    { name: "Delete Message", description: "Remove a message from a Telegram chat" },
    { name: "Get Chat Info", description: "Fetch metadata about a group or channel" },
    { name: "Pin Message", description: "Pin a message in a group or supergroup" },
    { name: "Send Poll", description: "Create a poll in a Telegram group" },
  ],
  slack: [
    { name: "Send Message", description: "Post a message to a Slack channel or user" },
    { name: "Send Blocks", description: "Send a rich block-kit formatted message" },
    { name: "Update Message", description: "Edit an existing Slack message by ts" },
    { name: "Add Reaction", description: "React to a message with an emoji" },
    { name: "Upload File", description: "Upload a file to a Slack channel" },
    { name: "Create Channel", description: "Create a new public or private channel" },
    { name: "Invite to Channel", description: "Add users to a Slack channel" },
    { name: "Get User Info", description: "Fetch user profile by email or user ID" },
  ],
  discord: [
    { name: "Send Message", description: "Post a message to a Discord channel" },
    { name: "Send Embed", description: "Post a rich embed card to a channel" },
    { name: "Edit Message", description: "Update an existing message by ID" },
    { name: "Delete Message", description: "Remove a message from a channel" },
    { name: "Add Role to User", description: "Assign a role to a Discord guild member" },
    { name: "Remove Role", description: "Remove a role from a guild member" },
    { name: "Create Thread", description: "Start a new thread in a channel" },
    { name: "Get Guild Members", description: "List members of a Discord guild" },
  ],
  whatsapp: [
    { name: "Send Text Message", description: "Send a text message via WhatsApp Business API" },
    { name: "Send Template Message", description: "Send a pre-approved template message" },
    { name: "Send Image", description: "Send an image via WhatsApp" },
    { name: "Send Document", description: "Send a file or PDF via WhatsApp" },
    { name: "Mark as Read", description: "Mark an incoming message as read" },
    { name: "Get Message Status", description: "Check delivery and read status of a message" },
  ],
  gmail: [
    { name: "Send Email", description: "Send an email from your Gmail account" },
    { name: "Reply to Email", description: "Reply to an existing email thread" },
    { name: "Forward Email", description: "Forward an email to another address" },
    { name: "Get Email", description: "Fetch a specific email by message ID" },
    { name: "Search Emails", description: "Search your Gmail inbox with a query" },
    { name: "Add Label", description: "Apply a label to an email" },
    { name: "Move to Trash", description: "Move an email to trash" },
    { name: "Create Draft", description: "Save an email as a draft" },
  ],
  twilio: [
    { name: "Send SMS", description: "Send a text message via Twilio" },
    { name: "Send WhatsApp", description: "Send a WhatsApp message through Twilio" },
    { name: "Make Phone Call", description: "Initiate an outbound phone call via Twilio" },
    { name: "Send Voice Message", description: "Play a TTS voice message on a call" },
    { name: "Lookup Phone Number", description: "Validate and enrich a phone number" },
    { name: "Get Message Status", description: "Check delivery status of a sent SMS" },
  ],
  sendgrid: [
    { name: "Send Email", description: "Send a transactional email via SendGrid" },
    { name: "Send Template Email", description: "Send an email using a dynamic template" },
    { name: "Add Contact", description: "Add a contact to your SendGrid marketing list" },
    { name: "Remove Contact", description: "Remove a contact from a marketing list" },
    { name: "Get Email Stats", description: "Fetch open, click, and bounce statistics" },
    { name: "Validate Email", description: "Check if an email address is valid" },
  ],

  // ── Integrations: Productivity ────────────────────────────────────────────────
  airtable: [
    { name: "List Records", description: "Fetch records from an Airtable base" },
    { name: "Create Record", description: "Add a new row to an Airtable table" },
    { name: "Update Record", description: "Modify fields of an existing record" },
    { name: "Delete Record", description: "Remove a record from a table" },
    { name: "Search Records", description: "Find records matching a formula filter" },
    { name: "Get Record", description: "Fetch a specific record by its ID" },
    { name: "Upsert Record", description: "Create or update based on a match field" },
  ],
  google_sheets: [
    { name: "Append Row", description: "Add a new row to the end of a sheet" },
    { name: "Update Row", description: "Update a specific row by its position or ID" },
    { name: "Read Rows", description: "Read a range of rows from a sheet" },
    { name: "Clear Range", description: "Delete values from a specified range" },
    { name: "Create Sheet", description: "Add a new tab to a Google Sheets workbook" },
    { name: "Lookup Row", description: "Find a row where a column matches a value" },
    { name: "Delete Row", description: "Remove a row by row number" },
    { name: "Batch Update", description: "Write multiple rows in one API call" },
  ],
  notion: [
    { name: "Create Page", description: "Create a new page in a Notion database" },
    { name: "Update Page", description: "Modify properties of an existing page" },
    { name: "Get Page", description: "Fetch a Notion page by its ID" },
    { name: "Query Database", description: "Filter and sort records in a Notion database" },
    { name: "Append Block", description: "Add content blocks to a Notion page" },
    { name: "Archive Page", description: "Archive (soft-delete) a Notion page" },
    { name: "Create Database", description: "Create a new Notion database" },
    { name: "Search Workspace", description: "Search pages and databases in Notion" },
  ],
  google_calendar: [
    { name: "Create Event", description: "Add a new event to a Google Calendar" },
    { name: "Update Event", description: "Modify an existing calendar event" },
    { name: "Delete Event", description: "Remove an event from the calendar" },
    { name: "Get Event", description: "Fetch a specific event by its ID" },
    { name: "List Events", description: "List events in a date range" },
    { name: "Quick Add Event", description: "Create an event from a natural language string" },
    { name: "Create Calendar", description: "Create a new calendar in the account" },
  ],
  google_drive: [
    { name: "Upload File", description: "Upload a file to a Google Drive folder" },
    { name: "Download File", description: "Download a file from Google Drive" },
    { name: "Create Folder", description: "Create a new folder in Google Drive" },
    { name: "List Files", description: "List files in a folder with optional filters" },
    { name: "Delete File", description: "Remove a file or folder from Drive" },
    { name: "Share File", description: "Change sharing permissions on a file" },
    { name: "Move File", description: "Move a file to a different folder" },
    { name: "Copy File", description: "Duplicate a file in Google Drive" },
  ],

  // ── Developer Tools ──────────────────────────────────────────────────────────
  github: [
    { name: "Create Issue", description: "Open a new issue in a GitHub repository" },
    { name: "Comment on Issue", description: "Add a comment to an existing issue" },
    { name: "Create Pull Request", description: "Open a new PR from a branch" },
    { name: "Merge Pull Request", description: "Merge a PR when checks pass" },
    { name: "Create File", description: "Commit a new file to a repository" },
    { name: "Get Repository", description: "Fetch metadata about a repository" },
    { name: "List Issues", description: "List open or closed issues" },
    { name: "Star Repository", description: "Star a GitHub repository" },
  ],
  jira: [
    { name: "Create Issue", description: "Create a new Jira ticket" },
    { name: "Update Issue", description: "Modify fields of an existing issue" },
    { name: "Transition Issue", description: "Move an issue to a different status" },
    { name: "Add Comment", description: "Add a comment to a Jira issue" },
    { name: "Search Issues (JQL)", description: "Query issues using Jira Query Language" },
    { name: "Get Issue", description: "Fetch a specific issue by its key" },
    { name: "Assign Issue", description: "Assign an issue to a team member" },
    { name: "Add Attachment", description: "Upload a file attachment to an issue" },
  ],
  linear: [
    { name: "Create Issue", description: "Create a new issue in a Linear team" },
    { name: "Update Issue", description: "Modify the state, priority, or fields of an issue" },
    { name: "Comment on Issue", description: "Add a comment to a Linear issue" },
    { name: "Get Issue", description: "Fetch an issue by its ID or identifier" },
    { name: "List Issues", description: "Query issues with filters and sorting" },
    { name: "Create Project", description: "Create a new project in Linear" },
    { name: "Assign Issue", description: "Assign an issue to a team member" },
  ],
  azure_devops: [
    { name: "Create Work Item", description: "Create a new task, bug, or user story" },
    { name: "Update Work Item", description: "Modify fields of an existing work item" },
    { name: "Get Work Item", description: "Fetch a specific work item by ID" },
    { name: "Query Work Items", description: "Run a WIQL query against work items" },
    { name: "Create Pipeline Run", description: "Trigger a CI/CD pipeline" },
    { name: "Get Build Status", description: "Check the result of a build pipeline" },
  ],
  sentry: [
    { name: "Create Issue", description: "Manually report an error to Sentry" },
    { name: "List Issues", description: "Fetch open issues from a Sentry project" },
    { name: "Resolve Issue", description: "Mark a Sentry issue as resolved" },
    { name: "Assign Issue", description: "Assign an issue to a team member" },
    { name: "Get Event", description: "Fetch a specific error event by its ID" },
  ],
  vercel: [
    { name: "Trigger Deployment", description: "Deploy a project via Vercel Deploy Hook" },
    { name: "Get Deployment Status", description: "Check if a deployment succeeded or failed" },
    { name: "List Deployments", description: "List recent deployments for a project" },
    { name: "Cancel Deployment", description: "Stop a running deployment" },
    { name: "Set Environment Variable", description: "Add or update an env var on a project" },
  ],
  netlify: [
    { name: "Trigger Build", description: "Kick off a build using a Netlify build hook" },
    { name: "Get Deploy Status", description: "Check the status of the latest deploy" },
    { name: "List Deploys", description: "Fetch recent deploy history for a site" },
    { name: "Cancel Deploy", description: "Cancel a currently running deploy" },
    { name: "Lock Production Deploy", description: "Prevent new deployments from going live" },
  ],
  pagerduty: [
    { name: "Create Incident", description: "Trigger a new PagerDuty incident" },
    { name: "Resolve Incident", description: "Resolve an active incident" },
    { name: "Acknowledge Incident", description: "Acknowledge an incident to stop escalation" },
    { name: "Add Note", description: "Add a note to an active incident" },
    { name: "Get On-call Users", description: "Find who is on-call for a schedule" },
  ],
  datadog: [
    { name: "Send Metric", description: "Post a custom metric to Datadog" },
    { name: "Create Event", description: "Send an event to the Datadog event stream" },
    { name: "Send Log", description: "Push a log entry to Datadog Logs" },
    { name: "Create Monitor", description: "Set up a Datadog alert monitor" },
    { name: "Mute Monitor", description: "Temporarily silence a Datadog monitor" },
  ],
  npm_package_info: [
    { name: "Get Package Info", description: "Fetch metadata for an npm package" },
    { name: "Get Latest Version", description: "Find the latest published version" },
    { name: "Check Vulnerabilities", description: "Scan for known CVEs in a package" },
    { name: "Download Stats", description: "Get weekly download count from npm" },
  ],
  semver_compare: [
    { name: "Compare Versions", description: "Check if version A is newer than version B" },
    { name: "Satisfies Range", description: "Check if a version satisfies a semver range" },
    { name: "Get Latest Matching", description: "Find the latest version matching a range" },
  ],
  docker_run: [
    { name: "Run Container", description: "Start a Docker container from an image" },
    { name: "Pull Image", description: "Pull a Docker image from a registry" },
    { name: "Exec in Container", description: "Run a command inside a running container" },
    { name: "Stop Container", description: "Gracefully stop a running container" },
    { name: "Remove Container", description: "Delete a stopped container" },
  ],
  ssh: [
    { name: "Execute Command", description: "Run a shell command on a remote server via SSH" },
    { name: "Transfer File (SCP)", description: "Upload or download a file via SCP" },
    { name: "Run Script", description: "Execute a multi-line script on a remote host" },
    { name: "Check Server Status", description: "Ping a server and verify it's reachable" },
  ],
  sftp: [
    { name: "Upload File", description: "Transfer a file to an SFTP server" },
    { name: "Download File", description: "Fetch a file from an SFTP server" },
    { name: "List Files", description: "List files in an SFTP directory" },
    { name: "Delete File", description: "Remove a file from an SFTP server" },
    { name: "Create Directory", description: "Create a new directory on an SFTP server" },
  ],
  graphql_request: [
    { name: "Execute Query", description: "Run a GraphQL query and return the response" },
    { name: "Execute Mutation", description: "Run a GraphQL mutation to create or update data" },
    { name: "Introspect Schema", description: "Fetch the GraphQL schema for a endpoint" },
  ],
  grpc_call: [
    { name: "Unary Call", description: "Make a single request/response gRPC call" },
    { name: "Server Streaming", description: "Open a gRPC server-side streaming request" },
    { name: "List Services", description: "Enumerate available gRPC services and methods" },
  ],
  webhook_response: [
    { name: "Respond with JSON", description: "Send a JSON response back to the webhook caller" },
    { name: "Respond with HTML", description: "Return an HTML page to the webhook caller" },
    { name: "Respond with Status", description: "Return a status code with an optional body" },
    { name: "Redirect", description: "Redirect the caller to another URL" },
  ],
  env_variable: [
    { name: "Get Variable", description: "Read an environment variable by name" },
    { name: "Set Variable", description: "Set an environment variable for this execution" },
    { name: "List Variables", description: "Return all visible environment variables" },
  ],
  docker: [
    { name: "List Containers", description: "List all running Docker containers" },
    { name: "Start Container", description: "Start a stopped Docker container" },
    { name: "Stop Container", description: "Stop a running Docker container" },
    { name: "Get Container Logs", description: "Fetch stdout/stderr logs from a container" },
    { name: "Build Image", description: "Build a Docker image from a Dockerfile" },
  ],
  ssl: [
    { name: "Check Certificate", description: "Verify the SSL cert for a domain" },
    { name: "Get Expiry Date", description: "Find when an SSL certificate expires" },
    { name: "Check Chain Validity", description: "Validate the full certificate chain" },
    { name: "Check HTTPS Redirect", description: "Verify HTTP redirects to HTTPS correctly" },
  ],
  dns: [
    { name: "DNS Lookup", description: "Resolve a domain to its IP address" },
    { name: "Reverse DNS", description: "Find the hostname for an IP address" },
    { name: "MX Record Lookup", description: "Find mail exchange records for a domain" },
    { name: "TXT Record Lookup", description: "Retrieve TXT records for a domain" },
    { name: "WHOIS Lookup", description: "Get registration info for a domain" },
  ],
  port_monitor: [
    { name: "Check Port", description: "Test if a specific port is open on a host" },
    { name: "Scan Ports", description: "Scan a range of ports on a host" },
    { name: "Check Service", description: "Verify a named service is listening" },
  ],
  http_monitor: [
    { name: "Check Uptime", description: "Ping an endpoint and return its status code" },
    { name: "Measure Response Time", description: "Record the latency of an HTTP request" },
    { name: "Check Response Body", description: "Assert that a response contains expected text" },
    { name: "Assert Status Code", description: "Fail if the response code doesn't match" },
  ],

  // ── CRM & Commerce ────────────────────────────────────────────────────────────
  stripe: [
    { name: "Create Payment Intent", description: "Start a Stripe payment intent" },
    { name: "Charge Customer", description: "Charge a stored card via a customer ID" },
    { name: "Create Customer", description: "Add a new customer to Stripe" },
    { name: "Create Subscription", description: "Subscribe a customer to a price plan" },
    { name: "Cancel Subscription", description: "Cancel an active Stripe subscription" },
    { name: "Refund Payment", description: "Issue a full or partial refund" },
    { name: "Get Invoice", description: "Fetch an invoice by ID" },
    { name: "Create Product", description: "Create a new product and price in Stripe" },
  ],
  hubspot: [
    { name: "Create Contact", description: "Add a new contact to HubSpot CRM" },
    { name: "Update Contact", description: "Modify contact properties" },
    { name: "Get Contact", description: "Fetch a contact by email or ID" },
    { name: "Create Deal", description: "Add a new deal to the pipeline" },
    { name: "Update Deal Stage", description: "Move a deal to a different pipeline stage" },
    { name: "Create Company", description: "Add a new company record" },
    { name: "Add Note", description: "Attach a note to a contact or deal" },
    { name: "Send Email via Sequences", description: "Enroll a contact in an email sequence" },
  ],
  shopify: [
    { name: "Create Order", description: "Place a new order in Shopify" },
    { name: "Get Order", description: "Fetch an order by its ID" },
    { name: "Update Order", description: "Modify an existing Shopify order" },
    { name: "Cancel Order", description: "Cancel an order and optionally issue a refund" },
    { name: "Create Product", description: "Add a new product listing" },
    { name: "Update Inventory", description: "Adjust stock levels for a variant" },
    { name: "Get Customer", description: "Fetch a Shopify customer by email" },
    { name: "Create Discount", description: "Generate a discount code" },
  ],
  zendesk: [
    { name: "Create Ticket", description: "Open a new support ticket in Zendesk" },
    { name: "Update Ticket", description: "Modify the status, priority, or fields" },
    { name: "Get Ticket", description: "Fetch a ticket by its ID" },
    { name: "Add Comment", description: "Post a public or internal reply" },
    { name: "Search Tickets", description: "Search tickets using Zendesk Query Language" },
    { name: "Assign Ticket", description: "Assign a ticket to an agent or group" },
  ],
  calendly: [
    { name: "Get Event Types", description: "List all booking types from your Calendly" },
    { name: "Get Scheduled Events", description: "Fetch upcoming scheduled meetings" },
    { name: "Cancel Event", description: "Cancel a scheduled Calendly event" },
    { name: "Get Invitee Info", description: "Fetch details about a Calendly invitee" },
    { name: "Create Single-use Link", description: "Generate a one-time booking link" },
  ],
  mailchimp: [
    { name: "Add Subscriber", description: "Add a contact to a Mailchimp audience" },
    { name: "Update Subscriber", description: "Modify subscriber tags or merge fields" },
    { name: "Remove Subscriber", description: "Unsubscribe or archive a contact" },
    { name: "Send Campaign", description: "Schedule and send an email campaign" },
    { name: "Get Campaign Stats", description: "Fetch opens, clicks, and bounces" },
    { name: "Add Tag", description: "Apply a tag to a subscriber" },
  ],
  clickup: [
    { name: "Create Task", description: "Create a new task in a ClickUp list" },
    { name: "Update Task", description: "Modify task fields like status, priority, or dates" },
    { name: "Get Task", description: "Fetch a specific task by its ID" },
    { name: "Add Comment", description: "Post a comment on a ClickUp task" },
    { name: "List Tasks", description: "Fetch all tasks in a list with filters" },
    { name: "Create Subtask", description: "Add a subtask to an existing task" },
  ],
  monday: [
    { name: "Create Item", description: "Add a new row to a Monday.com board" },
    { name: "Update Item", description: "Change column values of an existing item" },
    { name: "Get Item", description: "Fetch an item by its ID" },
    { name: "Create Update", description: "Post an update (comment) on an item" },
    { name: "Move Item to Group", description: "Move an item to a different board group" },
    { name: "Create Board", description: "Create a new Monday.com board" },
  ],
  asana: [
    { name: "Create Task", description: "Add a task to an Asana project" },
    { name: "Update Task", description: "Modify a task's fields or status" },
    { name: "Complete Task", description: "Mark a task as completed" },
    { name: "Add Comment", description: "Post a comment on a task" },
    { name: "Assign Task", description: "Assign a task to a team member" },
    { name: "Create Project", description: "Create a new project in Asana" },
  ],
  trello: [
    { name: "Create Card", description: "Add a new card to a Trello board" },
    { name: "Update Card", description: "Modify card fields like name, description, or due date" },
    { name: "Move Card", description: "Move a card to a different list" },
    { name: "Archive Card", description: "Archive a card from the board" },
    { name: "Add Comment", description: "Post a comment on a Trello card" },
    { name: "Add Label", description: "Apply a colored label to a card" },
    { name: "Create Checklist", description: "Add a checklist to a Trello card" },
  ],
  pipedrive: [
    { name: "Create Deal", description: "Add a new deal to Pipedrive" },
    { name: "Update Deal", description: "Modify deal fields or stage" },
    { name: "Create Contact", description: "Add a person or organization" },
    { name: "Create Activity", description: "Log a call, meeting, or task" },
    { name: "Get Deal", description: "Fetch a deal by its ID" },
    { name: "Search Deals", description: "Search deals by title or filters" },
  ],

  // ── Social Media ──────────────────────────────────────────────────────────────
  twitter: [
    { name: "Post Tweet", description: "Post a new tweet to your Twitter account" },
    { name: "Reply to Tweet", description: "Reply to an existing tweet" },
    { name: "Like Tweet", description: "Like a tweet by its ID" },
    { name: "Retweet", description: "Retweet a tweet to your followers" },
    { name: "Search Tweets", description: "Search recent tweets by keyword" },
    { name: "Follow User", description: "Follow a Twitter user by handle" },
    { name: "Get User Profile", description: "Fetch a user's profile and metrics" },
  ],
  instagram: [
    { name: "Get Profile", description: "Fetch an Instagram profile's public data" },
    { name: "Get Media", description: "List posts from a Business account" },
    { name: "Get Insights", description: "Fetch engagement metrics for a post" },
    { name: "Reply to Comment", description: "Post a reply to an Instagram comment" },
    { name: "Get Story Metrics", description: "Fetch impressions and reach for stories" },
  ],
  tiktok: [
    { name: "Get Profile", description: "Fetch a TikTok user's public profile" },
    { name: "Get Videos", description: "List videos from a TikTok account" },
    { name: "Get Video Metrics", description: "Fetch views, likes, and shares for a video" },
    { name: "Search Hashtag", description: "Search videos by a TikTok hashtag" },
  ],
  youtube: [
    { name: "Search Videos", description: "Search YouTube for videos by keyword" },
    { name: "Get Video Details", description: "Fetch title, description, and stats for a video" },
    { name: "Get Channel Info", description: "Fetch a YouTube channel's metadata and subscriber count" },
    { name: "List Channel Videos", description: "Get all uploaded videos for a channel" },
    { name: "Get Video Captions", description: "Fetch auto-generated or manual captions" },
    { name: "Get Comments", description: "List top comments on a video" },
  ],
  reddit: [
    { name: "Get Hot Posts", description: "Fetch the top hot posts from a subreddit" },
    { name: "Get New Posts", description: "Get the newest submissions in a subreddit" },
    { name: "Search Posts", description: "Search Reddit for posts matching a query" },
    { name: "Get Post Comments", description: "Fetch the top comments on a post" },
    { name: "Get User Profile", description: "Fetch public data for a Reddit user" },
  ],
  mastodon: [
    { name: "Post Toot", description: "Publish a new toot to your Mastodon account" },
    { name: "Boost Toot", description: "Reblog (boost) a toot from another account" },
    { name: "Search Hashtag", description: "Find toots tagged with a hashtag" },
    { name: "Get Timeline", description: "Fetch the public or local timeline" },
  ],
  hackernews: [
    { name: "Get Top Stories", description: "Fetch the current top Hacker News stories" },
    { name: "Get New Stories", description: "Get the newest HN submissions" },
    { name: "Get Story Details", description: "Fetch title, URL, and score for a story" },
    { name: "Get Comments", description: "Fetch top-level comments on a story" },
  ],
  producthunt: [
    { name: "Get Today's Launches", description: "Fetch products launched today on Product Hunt" },
    { name: "Search Products", description: "Search Product Hunt by keyword or topic" },
    { name: "Get Product Details", description: "Fetch votes, description, and maker info" },
    { name: "Get Trending Posts", description: "Get currently trending products" },
  ],

  // ── Social Media Publishing ─────────────────────────────────────────────────
  youtube_upload: [
    { name: "Upload Video", description: "Upload a video file to YouTube" },
    { name: "Update Video Metadata", description: "Edit title, description, or tags" },
    { name: "Set Thumbnail", description: "Upload a custom thumbnail for a video" },
    { name: "Publish Video", description: "Change a private video to public" },
  ],
  instagram_post: [
    { name: "Create Photo Post", description: "Publish a photo with caption to Instagram" },
    { name: "Create Carousel Post", description: "Post a multi-image carousel" },
    { name: "Create Reel", description: "Publish a short video Reel to Instagram" },
    { name: "Schedule Post", description: "Schedule a post for a future time" },
  ],
  tiktok_post: [
    { name: "Upload Video", description: "Upload a TikTok video to your account" },
    { name: "Post with Caption", description: "Publish a video with hashtags and caption" },
    { name: "Schedule Post", description: "Schedule a TikTok post for later" },
  ],
  linkedin_post: [
    { name: "Create Text Post", description: "Post a text update on LinkedIn" },
    { name: "Create Image Post", description: "Share an image with a caption" },
    { name: "Create Article", description: "Publish a long-form LinkedIn article" },
    { name: "Share URL Post", description: "Share a URL with a preview card" },
  ],
  twitter_post: [
    { name: "Post Tweet", description: "Publish a tweet to your Twitter timeline" },
    { name: "Post Thread", description: "Publish a threaded series of tweets" },
    { name: "Schedule Tweet", description: "Schedule a tweet for a future time" },
    { name: "Post with Media", description: "Attach an image or video to a tweet" },
  ],
  rss_feed_generator: [
    { name: "Generate RSS Feed", description: "Create an RSS feed from structured data" },
    { name: "Add Feed Item", description: "Append a new item to an RSS feed" },
    { name: "Validate Feed", description: "Check that an RSS or Atom feed is well-formed" },
  ],
  blog_post: [
    { name: "Create Post", description: "Publish a blog post via the CMS API" },
    { name: "Update Post", description: "Edit an existing blog post" },
    { name: "Publish Draft", description: "Change a draft to published status" },
    { name: "Add Tag", description: "Tag a blog post with a category or keyword" },
  ],
  thumbnail_generator: [
    { name: "Generate Thumbnail", description: "Create a thumbnail image from a template" },
    { name: "Overlay Text on Image", description: "Add a title or caption to an image" },
    { name: "Resize Image", description: "Scale an image to target dimensions" },
    { name: "Add Logo Watermark", description: "Place a branded watermark on an image" },
  ],
  hashtag_suggester: [
    { name: "Suggest Hashtags", description: "Generate relevant hashtags for a post" },
    { name: "Get Trending Hashtags", description: "Find what's trending on a platform" },
    { name: "Analyze Hashtag Reach", description: "Estimate reach for a given hashtag" },
  ],
  caption_writer: [
    { name: "Write Caption", description: "Generate a social media caption with AI" },
    { name: "Rewrite Caption", description: "Improve an existing caption's engagement" },
    { name: "Add Call to Action", description: "Append a strong CTA to a caption" },
  ],
  audience_insights: [
    { name: "Analyze Audience Demographics", description: "Understand your audience age, location, and interests" },
    { name: "Best Posting Times", description: "Find optimal times to post based on engagement history" },
    { name: "Top Performing Content", description: "Identify which content drives the most engagement" },
  ],

  // ── Design & Creative ─────────────────────────────────────────────────────────
  image_generate: [
    { name: "Generate Image (DALL·E)", description: "Create an image from a text prompt via DALL·E" },
    { name: "Generate Image (Stable Diffusion)", description: "Create an image via Stability AI" },
    { name: "Generate Image (Midjourney)", description: "Create via Midjourney API" },
    { name: "Image Variation", description: "Create a variation of an existing image" },
    { name: "Edit Image (Inpainting)", description: "Edit part of an image with a masked region" },
  ],
  image_caption: [
    { name: "Describe Image", description: "Generate an alt-text description of an image" },
    { name: "Extract Text from Image (OCR)", description: "Read text from a photo or screenshot" },
    { name: "Classify Image", description: "Label what's depicted in an image" },
    { name: "Detect Objects", description: "Identify objects and their bounding boxes" },
  ],
  remove_background: [
    { name: "Remove Background", description: "Cut out the background from a product photo" },
    { name: "Replace Background", description: "Swap the background with a new color or image" },
    { name: "Cutout Foreground", description: "Extract the main subject as a PNG with transparency" },
  ],
  font_preview: [
    { name: "Render Font Preview", description: "Preview custom text in a specific font" },
    { name: "List Available Fonts", description: "Browse available fonts from Google Fonts" },
    { name: "Download Font", description: "Fetch a font file for use in a project" },
  ],
  figma_comment: [
    { name: "Add Comment to File", description: "Post a comment on a Figma design file" },
    { name: "Get Comments", description: "Fetch all comments on a Figma file" },
    { name: "Resolve Comment", description: "Mark a comment as resolved" },
    { name: "Get File Nodes", description: "Extract layers and frames from a Figma file" },
  ],
  canva_export: [
    { name: "Export Design", description: "Export a Canva design as PNG, PDF, or MP4" },
    { name: "Create Design from Template", description: "Instantiate a Canva template with custom text" },
    { name: "Update Design Text", description: "Replace placeholder text in a Canva design" },
  ],
  figma: [
    { name: "Get File", description: "Fetch a Figma file's complete node tree" },
    { name: "Export Node as Image", description: "Export a specific frame or component" },
    { name: "Get Component", description: "Fetch a component by its key" },
    { name: "Get File History", description: "List version history for a Figma file" },
    { name: "Add Comment", description: "Post a comment on a Figma file" },
  ],

  // ── Education & AI Tools ─────────────────────────────────────────────────────
  flashcard_generator: [
    { name: "Generate Flashcards", description: "Create question-answer pairs from text" },
    { name: "Generate from PDF", description: "Extract and create flashcards from a PDF" },
    { name: "Export to Anki", description: "Format flashcards for import into Anki" },
  ],
  quiz_generator: [
    { name: "Generate Multiple Choice", description: "Create MCQ questions from a topic or text" },
    { name: "Generate True/False", description: "Create T/F questions from content" },
    { name: "Grade Answers", description: "Evaluate student answers and provide feedback" },
    { name: "Generate Essay Prompts", description: "Create open-ended essay questions" },
  ],
  citation_formatter: [
    { name: "Format in APA", description: "Convert reference data to APA format" },
    { name: "Format in MLA", description: "Convert reference data to MLA format" },
    { name: "Format in Chicago", description: "Convert reference data to Chicago format" },
    { name: "Extract URL Metadata", description: "Pull title, author, and date from a URL" },
  ],
  grammar_check: [
    { name: "Check Grammar", description: "Find and fix grammar errors in text" },
    { name: "Check Spelling", description: "Detect misspelled words and suggest corrections" },
    { name: "Check Readability", description: "Score text readability with Flesch-Kincaid" },
    { name: "Check Plagiarism", description: "Check text against known sources" },
  ],
  summarize: [
    { name: "Summarize Text", description: "Condense a long text into key bullet points" },
    { name: "Executive Summary", description: "Write a 3-sentence executive summary" },
    { name: "Summarize URL", description: "Fetch and summarize the content at a URL" },
    { name: "Summarize PDF", description: "Extract and summarize a PDF document" },
    { name: "Abstractive Summary", description: "Generate a flowing summary paragraph" },
  ],
  translation: [
    { name: "Translate Text", description: "Translate text to a target language" },
    { name: "Detect Language", description: "Identify the language of a given text" },
    { name: "Batch Translate", description: "Translate an array of strings in one call" },
    { name: "Transliterate", description: "Convert text to phonetic script" },
  ],
  text_to_speech: [
    { name: "Convert to Audio", description: "Convert text to a speech audio file" },
    { name: "Generate Voiceover", description: "Create a narration with a selected voice" },
    { name: "SSML to Audio", description: "Use SSML markup for expressive speech" },
  ],
  speech_to_text: [
    { name: "Transcribe Audio", description: "Convert an audio file to a text transcript" },
    { name: "Live Transcription", description: "Transcribe a live audio stream" },
    { name: "Speaker Diarization", description: "Separate and label different speakers" },
    { name: "Transcribe with Timestamps", description: "Return word-level timestamps" },
  ],
  ocr: [
    { name: "Extract Text from Image", description: "Read printed or handwritten text from a photo" },
    { name: "Extract from PDF", description: "OCR a scanned PDF document" },
    { name: "Extract Table from Image", description: "Parse a photo of a table into structured data" },
    { name: "Extract from Screenshot", description: "Pull text from a UI screenshot" },
  ],

  // ── Text Formatting ───────────────────────────────────────────────────────────
  number_format: [
    { name: "Format Currency", description: "Format a number as a currency string" },
    { name: "Format Percentage", description: "Convert a decimal to a percentage display" },
    { name: "Round to Decimal", description: "Round a number to N decimal places" },
    { name: "Add Thousands Separator", description: "Format large numbers with commas" },
  ],
  text_format: [
    { name: "Uppercase", description: "Convert text to uppercase" },
    { name: "Lowercase", description: "Convert text to lowercase" },
    { name: "Title Case", description: "Capitalize the first letter of each word" },
    { name: "Trim Whitespace", description: "Remove leading and trailing whitespace" },
    { name: "Truncate Text", description: "Shorten text to a max character count" },
    { name: "Pad Text", description: "Pad a string to a fixed length" },
  ],
  regex_match: [
    { name: "Test Pattern", description: "Check if a string matches a regex pattern" },
    { name: "Extract Matches", description: "Pull all regex matches from a string" },
    { name: "Replace Pattern", description: "Replace regex matches with a substitution" },
    { name: "Split by Pattern", description: "Split a string using a regex delimiter" },
  ],
  find_replace: [
    { name: "Find & Replace", description: "Replace all occurrences of a string" },
    { name: "Case-insensitive Replace", description: "Replace text regardless of case" },
    { name: "Replace with Regex", description: "Use a regex pattern for advanced replacement" },
  ],
  html_to_text: [
    { name: "Strip HTML Tags", description: "Remove all HTML markup from a string" },
    { name: "HTML to Markdown", description: "Convert HTML content to Markdown" },
    { name: "Parse HTML Links", description: "Extract all anchor tags and URLs from HTML" },
    { name: "Sanitize HTML", description: "Remove dangerous tags while keeping safe markup" },
  ],
  json_to_csv: [
    { name: "JSON Array to CSV", description: "Convert a JSON array of objects to CSV" },
    { name: "CSV to JSON", description: "Convert CSV text back to a JSON array" },
    { name: "Flatten Nested JSON", description: "Convert nested objects to flat CSV rows" },
  ],
  xml_parser: [
    { name: "Parse XML to JSON", description: "Convert an XML string to a JSON object" },
    { name: "JSON to XML", description: "Convert a JSON object to XML markup" },
    { name: "XPath Query", description: "Extract nodes from XML using an XPath expression" },
    { name: "Validate XML", description: "Check if an XML document is well-formed" },
  ],
  markdown_renderer: [
    { name: "Render Markdown to HTML", description: "Convert Markdown to HTML markup" },
    { name: "Render to Plain Text", description: "Strip Markdown syntax to plain text" },
    { name: "Extract Headings", description: "Pull all heading text from a Markdown document" },
    { name: "Extract Links", description: "Find all links in a Markdown document" },
  ],
  url_parser: [
    { name: "Parse URL", description: "Break a URL into protocol, host, path, and params" },
    { name: "Build URL", description: "Construct a URL from components" },
    { name: "Encode URL", description: "Percent-encode a URL or query string" },
    { name: "Extract Domain", description: "Pull just the domain from a URL" },
    { name: "Add Query Param", description: "Append or replace a URL query parameter" },
  ],

  // ── Finance & Accounting ──────────────────────────────────────────────────────
  gst_calculator: [
    { name: "Calculate GST", description: "Compute GST amount and total for a given rate" },
    { name: "Reverse GST Calculation", description: "Extract GST from a GST-inclusive price" },
    { name: "Generate GST Invoice", description: "Format a GST-compliant invoice summary" },
  ],
  invoice_parser: [
    { name: "Parse Invoice PDF", description: "Extract line items, totals, and vendor from a PDF" },
    { name: "Extract Invoice Fields", description: "Pull date, amount, and reference from text" },
    { name: "Validate Invoice Format", description: "Check that an invoice has all required fields" },
  ],
  tax_rate_lookup: [
    { name: "Get Tax Rate by Country", description: "Look up VAT/GST rate for a given country" },
    { name: "Get Sales Tax by US State", description: "Look up state-specific sales tax rate" },
    { name: "Check Tax Exemptions", description: "Determine if a category is tax-exempt" },
  ],
  bank_statement_parser: [
    { name: "Parse OFX/QFX File", description: "Extract transactions from a bank export" },
    { name: "Categorize Transactions", description: "Auto-label transactions by merchant type" },
    { name: "Generate Spending Summary", description: "Summarize total spend by category" },
  ],
  ledger_entry: [
    { name: "Create Journal Entry", description: "Record a debit/credit pair in the ledger" },
    { name: "Get Account Balance", description: "Fetch the current balance for an account" },
    { name: "List Transactions", description: "Query transactions for a date range" },
    { name: "Reconcile Account", description: "Match transactions against a bank statement" },
  ],
  currency_exchange: [
    { name: "Convert Currency", description: "Convert an amount from one currency to another" },
    { name: "Get Exchange Rate", description: "Fetch the live exchange rate between two currencies" },
    { name: "List Available Currencies", description: "Return all supported currency codes" },
    { name: "Historical Rate Lookup", description: "Get the exchange rate on a specific past date" },
  ],
  compound_interest: [
    { name: "Calculate Compound Interest", description: "Compute future value with compound interest" },
    { name: "Loan Amortization", description: "Generate a full loan repayment schedule" },
    { name: "Break-even Calculator", description: "Find the point where revenue equals cost" },
  ],
  payroll_calculator: [
    { name: "Calculate Net Pay", description: "Compute take-home pay after deductions" },
    { name: "Calculate Tax Withholding", description: "Estimate income tax withheld per paycheck" },
    { name: "Generate Pay Stub", description: "Format a structured pay stub object" },
  ],

  // ── Gaming ─────────────────────────────────────────────────────────────────────
  steam_game_lookup: [
    { name: "Get Game Info", description: "Fetch title, price, and metadata from Steam" },
    { name: "Get Player Stats", description: "Look up a player's Steam achievements and hours" },
    { name: "Search Games", description: "Find games on Steam by keyword" },
    { name: "Get Price History", description: "Fetch historical pricing for a Steam game" },
  ],
  twitch_stream_status: [
    { name: "Check Stream Live", description: "Check if a Twitch streamer is currently live" },
    { name: "Get Stream Info", description: "Fetch title, game, and viewer count" },
    { name: "Get Top Streams", description: "List the most-watched live streams" },
    { name: "Search Channels", description: "Find Twitch channels matching a query" },
  ],
  discord_role_assign: [
    { name: "Assign Role", description: "Give a Discord member a specific role" },
    { name: "Remove Role", description: "Take away a role from a Discord member" },
    { name: "List User Roles", description: "Fetch all roles for a Discord member" },
    { name: "Create Role", description: "Create a new role in a Discord server" },
  ],
  leaderboard_update: [
    { name: "Add Score", description: "Submit a score for a player" },
    { name: "Get Top N", description: "Fetch the top N scores on the leaderboard" },
    { name: "Get Player Rank", description: "Find a specific player's rank and score" },
    { name: "Reset Leaderboard", description: "Clear all scores for a new season" },
  ],
  game_event_webhook: [
    { name: "Emit Game Event", description: "Publish a game event to the webhook endpoint" },
    { name: "Listen for Event", description: "Register to receive game events" },
    { name: "Filter Event Type", description: "Only process events of a specific type" },
  ],

  // ── Automation Utilities ──────────────────────────────────────────────────────
  schedule_check: [
    { name: "Check Business Hours", description: "Return whether the current time is within business hours" },
    { name: "Is Weekend", description: "Check if today is a Saturday or Sunday" },
    { name: "Is Holiday", description: "Check if today is a public holiday" },
    { name: "Next Business Day", description: "Calculate the next working day" },
  ],
  ip_whitelist: [
    { name: "Check IP in Whitelist", description: "Allow or block a request based on its IP" },
    { name: "Add IP to Whitelist", description: "Add a trusted IP address to the list" },
    { name: "Remove IP from Whitelist", description: "Remove an IP from the trusted list" },
  ],
  pagination_handler: [
    { name: "Auto-paginate API", description: "Automatically fetch all pages of an API response" },
    { name: "Cursor-based Pagination", description: "Follow cursor tokens for paginated APIs" },
    { name: "Offset-based Pagination", description: "Increment page offset to collect all results" },
  ],
  file_upload: [
    { name: "Upload to S3", description: "Upload a file to an AWS S3 bucket" },
    { name: "Upload to GCS", description: "Upload a file to Google Cloud Storage" },
    { name: "Upload to Cloudinary", description: "Upload media to Cloudinary CDN" },
    { name: "Upload to R2", description: "Upload a file to Cloudflare R2" },
  ],
  file_download: [
    { name: "Download from URL", description: "Fetch a file from a public URL" },
    { name: "Download from S3", description: "Download a file from an AWS S3 bucket" },
    { name: "Download from GCS", description: "Download a file from Google Cloud Storage" },
  ],
  zip_files: [
    { name: "Create ZIP Archive", description: "Compress multiple files into a ZIP" },
    { name: "Extract ZIP", description: "Unzip a ZIP archive and list its contents" },
    { name: "Add File to ZIP", description: "Append a file to an existing ZIP archive" },
  ],
  hash: [
    { name: "SHA-256 Hash", description: "Compute the SHA-256 hash of any string" },
    { name: "MD5 Hash", description: "Compute the MD5 hash of a string" },
    { name: "bcrypt Hash", description: "Hash a password with bcrypt for secure storage" },
    { name: "bcrypt Verify", description: "Verify a password against a bcrypt hash" },
  ],
  virustotal: [
    { name: "Scan URL", description: "Submit a URL to VirusTotal for analysis" },
    { name: "Scan File Hash", description: "Check a file hash against known malware" },
    { name: "Get Report", description: "Fetch the analysis report for a submitted file or URL" },
    { name: "Search IOCs", description: "Search VirusTotal for indicators of compromise" },
  ],

  // ── Google Workspace ──────────────────────────────────────────────────────────
  google_docs: [
    { name: "Create Document", description: "Create a new Google Doc" },
    { name: "Append Text", description: "Append text to an existing Google Doc" },
    { name: "Get Document", description: "Fetch the full content of a Google Doc" },
    { name: "Replace Text", description: "Find and replace text inside a Google Doc" },
    { name: "Insert Image", description: "Add an image to a Google Doc" },
  ],
  google_forms: [
    { name: "Create Form", description: "Create a new Google Form" },
    { name: "Get Responses", description: "Fetch all responses to a Google Form" },
    { name: "Add Question", description: "Append a new question to an existing form" },
    { name: "Get Form Info", description: "Fetch form metadata including questions" },
  ],

  // ── Misc / Monitoring ────────────────────────────────────────────────────────
  rss: [
    { name: "Fetch RSS Feed", description: "Parse and return items from an RSS feed URL" },
    { name: "Get Latest Item", description: "Return only the most recent feed item" },
    { name: "Search Feed Items", description: "Filter feed items by keyword" },
    { name: "Subscribe to Feed", description: "Watch an RSS feed for new items" },
  ],
  database: [
    { name: "Execute SQL", description: "Run any SQL query against a connected database" },
    { name: "Insert Record", description: "Insert a row into a table" },
    { name: "Update Record", description: "Update rows matching a WHERE clause" },
    { name: "Delete Record", description: "Delete rows matching a WHERE clause" },
    { name: "Create Table", description: "Run a CREATE TABLE DDL statement" },
  ],
  price_alert: [
    { name: "Check Price Drop", description: "Check if a product's price fell below a threshold" },
    { name: "Check Price Rise", description: "Alert when a price exceeds a target" },
    { name: "Track Historical Price", description: "Log the current price for trend analysis" },
  ],
  cron: [
    { name: "Run on Schedule", description: "Execute on a cron schedule (e.g. every hour)" },
    { name: "Run Daily at Time", description: "Execute every day at a specific time" },
    { name: "Run Weekly", description: "Execute once a week on a specific day" },
  ],
  chat: [
    { name: "Reply to User", description: "Send a reply in the chat interface" },
    { name: "Ask a Question", description: "Ask the user a follow-up question" },
    { name: "Display Structured Data", description: "Show a formatted table or card to the user" },
  ],
  email: [
    { name: "Send Email", description: "Send an outbound email via SMTP" },
    { name: "Send HTML Email", description: "Send a rich HTML email" },
    { name: "Send Bulk Email", description: "Send emails to a list of recipients" },
    { name: "Parse Incoming Email", description: "Extract fields from an inbound email" },
  ],
  imap: [
    { name: "Read Emails", description: "Fetch recent emails from an IMAP mailbox" },
    { name: "Search Emails", description: "Search a mailbox with IMAP search criteria" },
    { name: "Mark as Read", description: "Mark a message as read in the inbox" },
    { name: "Move to Folder", description: "Move an email to a different IMAP folder" },
  ],
  error: [
    { name: "Catch Error", description: "Handle errors from a previous failed node" },
    { name: "Log Error", description: "Write the error details to a log" },
    { name: "Notify on Error", description: "Send an alert when an error is caught" },
    { name: "Retry on Error", description: "Automatically retry the failed node" },
  ],
};
