export default {
  backendType: "outlook",
  label: "Outlook",
  description: "Send emails, manage calendar events, read messages, and create contacts in Microsoft Outlook.",
  fields: [
    { type: "notice", variant: "info", text: "Requires a Microsoft 365 OAuth credential with Mail, Calendar, and Contacts permissions." },
    { name: "credentialId", label: "Microsoft 365 OAuth", type: "credential", accentColor: "#0072C6" },
    { name: "operation", label: "Operation", type: "options", cols: 3, default: "sendEmail", options: [
      { value: "sendEmail",    label: "Send Email" },
      { value: "getEmail",     label: "Get Email" },
      { value: "listEmails",   label: "List Emails" },
      { value: "replyEmail",   label: "Reply to Email" },
      { value: "moveEmail",    label: "Move Email" },
      { value: "flagEmail",    label: "Flag Email" },
      { value: "createEvent",  label: "Create Event" },
      { value: "getCalendar",  label: "Get Calendar" },
      { value: "createContact", label: "Create Contact" },
    ]},
    { name: "to", label: "To", type: "string", smart: true, show: { operation: "sendEmail" } },
    { name: "subject", label: "Subject", type: "string", smart: true, show: { operation: "sendEmail" } },
    { name: "body", label: "Body", type: "string", smart: true, multiline: true, show: { operation: ["sendEmail","replyEmail"] } },
    { name: "cc", label: "CC (optional)", type: "string", smart: true, show: { operation: "sendEmail" } },
    { name: "bcc", label: "BCC (optional)", type: "string", smart: true, show: { operation: "sendEmail" } },
    { name: "isHtml", label: "HTML Body", type: "boolean", default: true, show: { operation: "sendEmail" } },
    { name: "messageId", label: "Message ID", type: "string", smart: true, show: { operation: ["getEmail","replyEmail","moveEmail","flagEmail"] } },
    { name: "folder", label: "Folder", type: "string", default: "inbox", show: { operation: "listEmails" } },
    { name: "limit", label: "Limit", type: "number", default: 20, show: { operation: "listEmails" } },
    { name: "search", label: "Search (optional)", type: "string", smart: true, show: { operation: "listEmails" } },
    { name: "replyAll", label: "Reply All", type: "boolean", default: false, show: { operation: "replyEmail" } },
    { name: "destinationFolder", label: "Destination Folder", type: "string", smart: true, placeholder: "Inbox/Subfolder", show: { operation: "moveEmail" } },
    { name: "flagStatus", label: "Flag Status", type: "options", cols: 3, options: [
      { value: "flagged",    label: "Flagged" },
      { value: "notFlagged", label: "Not Flagged" },
      { value: "complete",   label: "Complete" },
    ], show: { operation: "flagEmail" } },
    { name: "eventSubject", label: "Subject", type: "string", smart: true, show: { operation: "createEvent" } },
    { name: "start", label: "Start", type: "string", smart: true, placeholder: "2024-12-25T10:00:00", show: { operation: "createEvent" } },
    { name: "end", label: "End", type: "string", smart: true, placeholder: "2024-12-25T11:00:00", show: { operation: "createEvent" } },
    { name: "attendees", label: "Attendees", type: "string", smart: true, multiline: true, hint: "One email per line", show: { operation: "createEvent" } },
    { name: "eventBody", label: "Body (optional)", type: "string", smart: true, multiline: true, show: { operation: "createEvent" } },
    { name: "isOnline", label: "Online Meeting", type: "boolean", default: false, show: { operation: "createEvent" } },
    { name: "calendarId", label: "Calendar ID (optional)", type: "string", smart: true, hint: "Leave blank to use the default calendar", show: { operation: "getCalendar" } },
    { name: "displayName", label: "Display Name", type: "string", smart: true, show: { operation: "createContact" } },
    { name: "email", label: "Email", type: "string", smart: true, show: { operation: "createContact" } },
    { name: "phone", label: "Phone (optional)", type: "string", smart: true, show: { operation: "createContact" } },
    { name: "company", label: "Company (optional)", type: "string", smart: true, show: { operation: "createContact" } },
  ],
  outputs: ["message", "messages", "event", "calendar", "contact"],
};
