export default {
  backendType: "number_format",
  label: "Number Format",
  description: "Round, format, or convert a number",
  fields: [
    {
      name: "field",
      label: "Input Field",
      type: "string",
      smart: true,
      placeholder: "{{ $json.price }}",
    },
    {
      name: "operation",
      label: "Operation",
      type: "options",
      cols: 2,
      default: "round",
      options: [
        { value: "round",    label: "Round" },
        { value: "floor",    label: "Floor" },
        { value: "ceil",     label: "Ceil" },
        { value: "fixed",    label: "Fixed Decimals" },
        { value: "currency", label: "Currency" },
        { value: "percent",  label: "Percentage" },
        { value: "abs",      label: "Absolute Value" },
        { value: "pad",      label: "Zero Pad" },
      ],
    },
    {
      name: "decimals",
      label: "Decimal Places",
      type: "number",
      min: 0,
      max: 10,
      default: 2,
      show: { operation: ["fixed", "currency", "percent"] },
    },
    {
      name: "currency",
      label: "Currency",
      type: "options",
      cols: 4,
      default: "USD",
      options: ["USD", "EUR", "GBP", "INR", "JPY", "AUD", "CAD"],
      show: { operation: "currency" },
    },
    {
      name: "padLength",
      label: "Pad Length",
      type: "number",
      min: 1,
      max: 20,
      default: 6,
      show: { operation: "pad" },
    },
    {
      name: "outputField",
      label: "Output Field",
      type: "string",
      smart: false,
      mono: true,
      placeholder: "result",
      default: "result",
    },
  ],
  outputs: ["result"],
};
