export default {
  backendType: "mongodb",
  label: "MongoDB",
  description: "Query, insert, update, delete, and aggregate documents in a MongoDB collection.",
  fields: [
    { name: "credentialId", type: "credential", label: "MongoDB Credential", accentColor: "#4DB33D" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "findOne", options: [
      { value: "findOne",     label: "Find One" },
      { value: "find",        label: "Find" },
      { value: "insertOne",   label: "Insert One" },
      { value: "insertMany",  label: "Insert Many" },
      { value: "updateOne",   label: "Update One" },
      { value: "updateMany",  label: "Update Many" },
      { value: "deleteOne",   label: "Delete One" },
      { value: "deleteMany",  label: "Delete Many" },
      { value: "aggregate",   label: "Aggregate" },
      { value: "count",       label: "Count" },
    ]},
    { name: "database", type: "string", label: "Database", smart: true, placeholder: "myDatabase" },
    { name: "collection", type: "string", label: "Collection", smart: true, placeholder: "users" },
    { name: "query", type: "string", label: "Query", smart: true, multiline: true, default: "{}",
      hint: "JSON filter object",
      show: { operation: ["findOne","find","count"] } },
    { name: "projection", type: "string", label: "Projection", smart: true,
      hint: "JSON projection",
      show: { operation: ["findOne","find"] } },
    { name: "sort", type: "string", label: "Sort", smart: true,
      hint: "JSON: {field:1}",
      show: { operation: ["find"] } },
    { name: "limit", type: "number", label: "Limit", default: 100,
      show: { operation: ["find"] } },
    { name: "skip", type: "number", label: "Skip", default: 0,
      show: { operation: ["find"] } },
    { name: "document", type: "string", label: "Document", smart: true, multiline: true,
      hint: "JSON document to insert",
      show: { operation: ["insertOne"] } },
    { name: "documents", type: "string", label: "Documents", smart: true, multiline: true,
      hint: "JSON array of documents",
      show: { operation: ["insertMany"] } },
    { name: "filter", type: "string", label: "Filter", smart: true, multiline: true,
      hint: "JSON filter",
      show: { operation: ["updateOne","updateMany","deleteOne","deleteMany"] } },
    { name: "update", type: "string", label: "Update", smart: true, multiline: true,
      hint: "JSON update: {$set: {field: value}}",
      show: { operation: ["updateOne"] } },
    { name: "update", type: "string", label: "Update", smart: true, multiline: true,
      hint: "JSON update operator",
      show: { operation: ["updateMany"] } },
    { name: "upsert", type: "boolean", label: "Upsert", default: false,
      show: { operation: ["updateOne","updateMany"] } },
    { name: "pipeline", type: "string", label: "Pipeline", smart: true, multiline: true,
      hint: "JSON array of aggregation stages",
      show: { operation: ["aggregate"] } },
  ],
  outputs: ["document","documents","insertedId","modifiedCount","deletedCount","count"],
};
