export default {
  backendType: "dropbox",
  label: "Dropbox",
  description: "List, upload, download, move, and share files and folders in Dropbox.",
  fields: [
    { name: "credentialId", type: "credential", label: "Dropbox Credential", accentColor: "#0061FF" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "listFiles", options: [
      { value: "listFiles",    label: "List Files" },
      { value: "uploadFile",   label: "Upload File" },
      { value: "downloadFile", label: "Download File" },
      { value: "createFolder", label: "Create Folder" },
      { value: "deleteFile",   label: "Delete File" },
      { value: "moveFile",     label: "Move File" },
      { value: "getFileInfo",  label: "Get File Info" },
      { value: "searchFiles",  label: "Search Files" },
      { value: "shareFile",    label: "Share File" },
    ]},
    { name: "path", type: "string", label: "Path", smart: true, default: "/", placeholder: "/Documents",
      show: { operation: ["listFiles","downloadFile","deleteFile","getFileInfo","shareFile"] } },
    { name: "recursive", type: "boolean", label: "Recursive", default: false,
      show: { operation: ["listFiles"] } },
    { name: "limit", type: "number", label: "Limit", default: 100,
      show: { operation: ["listFiles"] } },
    { name: "path", type: "string", label: "Destination Path", smart: true, placeholder: "/Documents/file.txt",
      show: { operation: ["uploadFile"] } },
    { name: "content", type: "string", label: "File Content", smart: true, multiline: true,
      hint: "File content",
      show: { operation: ["uploadFile"] } },
    { name: "overwrite", type: "boolean", label: "Overwrite", default: true,
      show: { operation: ["uploadFile"] } },
    { name: "fromPath", type: "string", label: "From Path", smart: true,
      show: { operation: ["moveFile"] } },
    { name: "toPath", type: "string", label: "To Path", smart: true,
      show: { operation: ["moveFile"] } },
    { name: "overwrite", type: "boolean", label: "Overwrite", default: false,
      show: { operation: ["moveFile"] } },
    { name: "query", type: "string", label: "Search Query", smart: true, placeholder: "report.pdf",
      show: { operation: ["searchFiles"] } },
    { name: "searchPath", type: "string", label: "Search In Path", smart: true, placeholder: "/Documents",
      show: { operation: ["searchFiles"] } },
    { name: "requestedVisibility", type: "options", label: "Visibility", cols: 3, default: "public",
      options: [
        { value: "public",        label: "Public" },
        { value: "team_only",     label: "Team Only" },
        { value: "password",      label: "Password" },
      ],
      show: { operation: ["shareFile"] } },
  ],
  outputs: ["file","files","path","url","metadata"],
};
