const QUERY_OPERATORS = [
  { value: "==", label: "=" },
  { value: "!=", label: "≠" },
  { value: ">", label: ">" },
  { value: ">=", label: "≥" },
  { value: "<", label: "<" },
  { value: "<=", label: "≤" },
  { value: "array-contains", label: "Contains" },
  { value: "array-contains-any", label: "Contains Any" },
  { value: "in", label: "In" },
  { value: "not-in", label: "Not In" },
];

const DOC_OPS = ["getDocument", "setDocument", "updateDocument", "deleteDocument", "incrementField"];

export default {
  backendType: "firebase",
  label: "Firebase",
  description: "Read and write Firestore documents, manage auth users, and send push notifications.",
  fields: [
    { name: "credentialId", type: "credential", label: "Firebase Credential", accentColor: "#FFCA28" },

    { name: "collection", type: "string", label: "Collection", smart: true, required: true, placeholder: "users",
      show: { operation: [...DOC_OPS, "addDocument", "queryCollection", "countCollection", "batchSet"] } },
    { name: "docId", type: "string", label: "Document ID", smart: true, required: true, placeholder: "{{ $json.userId }}",
      show: { operation: DOC_OPS } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true, required: true,
      hint: "JSON object of field → value",
      show: { operation: ["setDocument", "addDocument", "updateDocument"] } },
    { name: "merge", type: "boolean", label: "Merge With Existing", default: true,
      hint: "Off replaces the whole document",
      show: { operation: ["setDocument", "batchSet"] } },
    { name: "documents", type: "string", label: "Documents", smart: true, multiline: true, required: true,
      hint: "JSON array of objects, each with an id field",
      show: { operation: ["batchSet"] } },

    { name: "field", type: "string", label: "Field", smart: true, placeholder: "status",
      show: { operation: ["queryCollection", "countCollection"] } },
    { name: "field", type: "string", label: "Field", smart: true, required: true, placeholder: "views",
      show: { operation: ["incrementField"] } },
    { name: "operator", type: "options", label: "Operator", default: "==", options: QUERY_OPERATORS,
      show: { operation: ["queryCollection", "countCollection"] } },
    { name: "filterValue", type: "string", label: "Value", smart: true, placeholder: "{{ $json.status }}",
      show: { operation: ["queryCollection", "countCollection"] } },
    { name: "orderBy", type: "string", label: "Order By", smart: true, placeholder: "createdAt",
      show: { operation: ["queryCollection"] } },
    { name: "orderDir", type: "options", label: "Direction", default: "asc", options: [
      { value: "asc", label: "Ascending" },
      { value: "desc", label: "Descending" },
    ], show: { operation: ["queryCollection"] } },
    { name: "limit", type: "number", label: "Limit", default: 100,
      show: { operation: ["queryCollection", "listUsers"] } },
    { name: "by", type: "number", label: "Increment By", default: 1,
      hint: "Use a negative number to decrease",
      show: { operation: ["incrementField"] } },

    { name: "userId", type: "string", label: "User ID", smart: true, required: true,
      show: { operation: ["deleteUser", "updateUser", "setCustomClaims", "createCustomToken"] } },
    { name: "userId", type: "string", label: "User ID", smart: true,
      hint: "Provide either a user ID or an email",
      show: { operation: ["getUser"] } },
    { name: "email", type: "string", label: "Email", smart: true,
      show: { operation: ["getUser", "updateUser"] } },
    { name: "email", type: "string", label: "Email", smart: true, required: true, placeholder: "{{ $json.email }}",
      show: { operation: ["createUser"] } },
    { name: "password", type: "string", label: "Password", smart: true,
      show: { operation: ["createUser", "updateUser"] } },
    { name: "displayName", type: "string", label: "Display Name", smart: true,
      show: { operation: ["createUser", "updateUser"] } },
    { name: "phoneNumber", type: "string", label: "Phone Number", smart: true, placeholder: "+15551234567",
      show: { operation: ["updateUser"] } },
    { name: "disabled", type: "boolean", label: "Disable Account", default: false,
      show: { operation: ["updateUser"] } },
    { name: "pageToken", type: "string", label: "Page Token", smart: true,
      hint: "Returned by the previous run to fetch the next page",
      show: { operation: ["listUsers"] } },
    { name: "claims", type: "string", label: "Claims", smart: true, multiline: true, required: true,
      hint: "JSON object baked into the user's token: {\"admin\": true}",
      show: { operation: ["setCustomClaims"] } },
    { name: "claims", type: "string", label: "Claims", smart: true, multiline: true,
      hint: "Optional JSON object embedded in the token",
      show: { operation: ["createCustomToken"] } },

    { name: "token", type: "string", label: "Device Token", smart: true, required: true,
      hint: "The FCM registration token for the target device",
      show: { operation: ["sendToToken"] } },
    { name: "topic", type: "string", label: "Topic", smart: true, required: true, placeholder: "news",
      show: { operation: ["sendToTopic", "subscribeToTopic", "unsubscribeFromTopic"] } },
    { name: "tokens", type: "string", label: "Device Tokens", smart: true, multiline: true, required: true,
      hint: "Comma-separated, or a JSON array",
      show: { operation: ["subscribeToTopic", "unsubscribeFromTopic"] } },
    { name: "title", type: "string", label: "Title", smart: true, required: true,
      show: { operation: ["sendToToken", "sendToTopic"] } },
    { name: "body", type: "string", label: "Body", smart: true, multiline: true,
      show: { operation: ["sendToToken", "sendToTopic"] } },
    { name: "data", type: "string", label: "Payload", smart: true, multiline: true,
      hint: "JSON object of extra values delivered with the notification",
      show: { operation: ["sendToToken", "sendToTopic"] } },
  ],
  outputs: ["document", "documents", "id", "data", "exists", "count", "collections", "user", "users", "pageToken", "token", "messageId", "successCount", "failureCount"],
};
