export default {
  backendType: "firebase",
  label: "Firebase",
  description: "Read, write, query, and update documents in a Firebase Firestore database.",
  fields: [
    { name: "credentialId", type: "credential", label: "Firebase Credential", accentColor: "#FFCA28" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "getDocument", options: [
      { value: "getDocument",      label: "Get Document" },
      { value: "setDocument",      label: "Set Document" },
      { value: "updateDocument",   label: "Update Document" },
      { value: "deleteDocument",   label: "Delete Document" },
      { value: "queryCollection",  label: "Query Collection" },
      { value: "incrementField",   label: "Increment Field" },
      { value: "addToArray",       label: "Add to Array" },
      { value: "removeFromArray",  label: "Remove from Array" },
    ]},
    { name: "projectId", type: "string", label: "Project ID", smart: false, placeholder: "my-firebase-project" },
    { name: "collection", type: "string", label: "Collection", smart: true, placeholder: "users",
      show: { operation: ["getDocument","setDocument","updateDocument","deleteDocument","queryCollection","incrementField","addToArray","removeFromArray"] } },
    { name: "documentId", type: "string", label: "Document ID", smart: true,
      show: { operation: ["getDocument","setDocument","updateDocument","deleteDocument","incrementField","addToArray","removeFromArray"] } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true,
      hint: "JSON object",
      show: { operation: ["setDocument"] } },
    { name: "merge", type: "boolean", label: "Merge", default: true,
      show: { operation: ["setDocument"] } },
    { name: "fields", type: "string", label: "Fields", smart: true, multiline: true,
      hint: "JSON object of fields to update",
      show: { operation: ["updateDocument"] } },
    { name: "where", type: "string", label: "Where", smart: true, multiline: true,
      hint: "JSON array: [{field,op,value}]",
      show: { operation: ["queryCollection"] } },
    { name: "orderBy", type: "string", label: "Order By", smart: true,
      show: { operation: ["queryCollection"] } },
    { name: "limit", type: "number", label: "Limit", default: 20,
      show: { operation: ["queryCollection"] } },
    { name: "field", type: "string", label: "Field", smart: true,
      show: { operation: ["incrementField","addToArray","removeFromArray"] } },
    { name: "amount", type: "number", label: "Amount", default: 1,
      show: { operation: ["incrementField"] } },
    { name: "value", type: "string", label: "Value", smart: true,
      show: { operation: ["addToArray","removeFromArray"] } },
  ],
  outputs: ["document","documents","id","data"],
};
