export default {
  backendType: "http_request",
  label: "HTTP Request",
  description: "Call any REST API with headers, auth, body and retries.",
  fields: [
    { name: "method", type: "options", label: "Method", default: "GET", options: [
      { value: "GET",    label: "GET" },
      { value: "POST",   label: "POST" },
      { value: "PUT",    label: "PUT" },
      { value: "PATCH",  label: "PATCH" },
      { value: "DELETE", label: "DELETE" },
    ]},
    { name: "url", type: "string", label: "URL", smart: true,
      placeholder: "https://api.example.com/v1/users" },
    { name: "credentialId", type: "credential", label: "Authentication", accentColor: "blue",
      hint: "Bearer, API key or basic auth is injected for you. Leave blank for public endpoints." },
    { name: "queryParams", type: "keyValue", label: "Query Parameters",
      keyPlaceholder: "page", valuePlaceholder: "1", addLabel: "Add parameter" },
    { name: "headers", type: "keyValue", label: "Headers",
      keyPlaceholder: "X-Custom-Header", valuePlaceholder: "value", addLabel: "Add header" },
    { name: "body", type: "string", label: "Body", smart: true, multiline: true,
      hint: "Sent as JSON. Reference earlier steps with {{ }}.",
      show: { method: ["POST", "PUT", "PATCH"] } },
    { name: "responseType", type: "options", label: "Response", default: "auto", options: [
      { value: "auto",   label: "Auto Detect" },
      { value: "json",   label: "JSON" },
      { value: "binary", label: "File" },
    ], hint: "Auto stores images, PDFs and archives as files and parses everything else." },
    { name: "timeout", type: "number", label: "Timeout", default: 15000,
      hint: "Milliseconds. Capped at 60000." },
    { name: "followRedirects", type: "boolean", label: "Follow Redirects", default: true },
  ],
  outputs: ["data", "status", "statusText", "headers"],
};
