/* GENERATED by scripts/gen-themes.mjs — do not edit by hand. */
export const THEME_STORAGE_KEY = 'bb-theme';

export const THEMES = [
  {
    id: 'graphite',
    label: 'Graphite',
    blurb: 'The original neutral dark.',
    isDefault: true,
    swatch: [
      '#0c0c0c',
      '#262626',
      '#6f97e8'
    ]
  },
  {
    id: 'midnight',
    label: 'Midnight',
    blurb: 'Cool blue-black, deep focus.',
    isDefault: false,
    swatch: [
      '#080c15',
      '#202632',
      '#7097e8'
    ]
  },
  {
    id: 'ember',
    label: 'Ember',
    blurb: 'Warm charcoal with amber heat.',
    isDefault: false,
    swatch: [
      '#120a05',
      '#2f231b',
      '#d38340'
    ]
  },
  {
    id: 'abyss',
    label: 'Abyss',
    blurb: 'Deep sea slate and teal.',
    isDefault: false,
    swatch: [
      '#030f0f',
      '#182a2a',
      '#00afab'
    ]
  },
  {
    id: 'orchid',
    label: 'Orchid',
    blurb: 'Plum shadows, violet light.',
    isDefault: false,
    swatch: [
      '#100911',
      '#2b222d',
      '#a984da'
    ]
  }
];

export const DEFAULT_THEME = 'graphite';
