export default {
  backendType: "sharepoint",
  label: "SharePoint",
  description: "List sites, manage files and folders in Microsoft SharePoint document libraries.",
  fields: [
    { name: "credentialId", type: "credential", label: "Microsoft Credential", accentColor: "#038387" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "listFiles", options: [
      { value: "listSites",    label: "List Sites" },
      { value: "listFiles",    label: "List Files" },
      { value: "uploadFile",   label: "Upload File" },
      { value: "downloadFile", label: "Download File" },
      { value: "createFolder", label: "Create Folder" },
      { value: "deleteFile",   label: "Delete File" },
      { value: "searchFiles",  label: "Search Files" },
    ]},
    { name: "siteId", type: "string", label: "Site ID", smart: true,
      hint: "Leave blank to use root site" },
    { name: "limit", type: "number", label: "Limit", default: 20,
      show: { operation: ["listSites"] } },
    { name: "driveId", type: "string", label: "Drive ID", smart: true,
      show: { operation: ["listFiles","uploadFile","downloadFile","createFolder","deleteFile","searchFiles"] } },
    { name: "folderId", type: "string", label: "Folder ID", smart: true, default: "root",
      show: { operation: ["listFiles"] } },
    { name: "fileName", type: "string", label: "File Name", smart: true,
      show: { operation: ["uploadFile"] } },
    { name: "content", type: "string", label: "File Content", smart: true, multiline: true,
      show: { operation: ["uploadFile"] } },
    { name: "parentFolderId", type: "string", label: "Parent Folder ID", smart: true, default: "root",
      show: { operation: ["uploadFile","createFolder"] } },
    { name: "itemId", type: "string", label: "Item ID", smart: true,
      show: { operation: ["downloadFile","deleteFile"] } },
    { name: "name", type: "string", label: "Folder Name", smart: true,
      show: { operation: ["createFolder"] } },
    { name: "query", type: "string", label: "Search Query", smart: true,
      show: { operation: ["searchFiles"] } },
  ],
  outputs: ["sites","files","file","folder","url"],
};
