export default {
  backendType: "google_docs",
  label: "Google Docs",
  description: "Create, read, append, update, and list Google Docs documents.",
  fields: [
    { name: "credentialId", type: "credential", label: "Google Credential", accentColor: "#4285F4" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "createDocument", options: [
      { value: "createDocument", label: "Create Document" },
      { value: "getDocument",    label: "Get Document" },
      { value: "appendText",     label: "Append Text" },
      { value: "updateText",     label: "Update Text" },
      { value: "listDocuments",  label: "List Documents" },
    ]},
    { name: "title", type: "string", label: "Title", smart: true,
      show: { operation: ["createDocument"] } },
    { name: "body", type: "string", label: "Body", smart: true, multiline: true,
      show: { operation: ["createDocument"] } },
    { name: "documentId", type: "string", label: "Document ID", smart: true,
      show: { operation: ["getDocument","appendText","updateText"] } },
    { name: "text", type: "string", label: "Text", smart: true, multiline: true,
      show: { operation: ["appendText","updateText"] } },
    { name: "range", type: "string", label: "Range", smart: true,
      show: { operation: ["updateText"] } },
    { name: "pageSize", type: "number", label: "Page Size", default: 20,
      show: { operation: ["listDocuments"] } },
    { name: "query", type: "string", label: "Query", smart: true, placeholder: "name contains 'report'",
      show: { operation: ["listDocuments"] } },
  ],
  outputs: ["documentId","document","text","title","url"],
};
