const FILTER_OPERATORS = [
  { value: "eq", label: "=" },
  { value: "neq", label: "≠" },
  { value: "gt", label: ">" },
  { value: "gte", label: "≥" },
  { value: "lt", label: "<" },
  { value: "lte", label: "≤" },
  { value: "like", label: "Like" },
  { value: "ilike", label: "Like (no case)" },
  { value: "in", label: "In" },
  { value: "is", label: "Is" },
  { value: "contains", label: "Contains" },
  { value: "containedBy", label: "Contained By" },
];

export default {
  backendType: "supabase",
  label: "Supabase",
  description: "Read and write tables, call RPC functions, manage auth users and storage files.",
  fields: [
    { name: "credentialId", type: "credential", label: "Supabase Credential", accentColor: "#3ECF8E" },

    { name: "table", type: "string", label: "Table", smart: true, required: true, placeholder: "users",
      show: { operation: ["select", "selectSingle", "insert", "update", "upsert", "delete", "count", "deleteAll"] } },
    { name: "column", type: "string", label: "Columns", smart: true, default: "*",
      hint: "Comma-separated, or * for every column",
      show: { operation: ["select", "selectSingle"] } },

    { name: "filter", type: "string", label: "Filter Column", smart: true, placeholder: "status",
      show: { operation: ["select", "selectSingle", "update", "delete", "count"] } },
    { name: "filterOperator", type: "options", label: "Filter Operator", default: "eq", options: FILTER_OPERATORS,
      show: { operation: ["select", "selectSingle", "update", "delete", "count"] } },
    { name: "filterValue", type: "string", label: "Filter Value", smart: true, placeholder: "{{ $json.status }}",
      show: { operation: ["select", "selectSingle", "update", "delete", "count"] } },

    { name: "filterColumn2", type: "string", label: "Second Filter Column", smart: true,
      hint: "Optional — narrows the result further",
      show: { operation: ["select"] } },
    { name: "filterOperator2", type: "options", label: "Second Filter Operator", default: "eq", options: FILTER_OPERATORS,
      show: { operation: ["select"] } },
    { name: "filterValue2", type: "string", label: "Second Filter Value", smart: true,
      show: { operation: ["select"] } },

    { name: "orderBy", type: "string", label: "Order By", smart: true, placeholder: "created_at",
      show: { operation: ["select"] } },
    { name: "orderAsc", type: "boolean", label: "Ascending", default: true,
      show: { operation: ["select"] } },
    { name: "limit", type: "number", label: "Limit", default: 100,
      show: { operation: ["select", "listUsers", "listFiles"] } },

    { name: "data", type: "string", label: "Data", smart: true, multiline: true, required: true,
      hint: "JSON object, or an array of objects to write many rows at once",
      show: { operation: ["insert", "update", "upsert"] } },
    { name: "conflictColumns", type: "string", label: "Conflict Columns", smart: true, placeholder: "id",
      hint: "Comma-separated unique columns that trigger the update",
      show: { operation: ["upsert"] } },
    { name: "confirm", type: "boolean", label: "Confirm Delete All", default: false,
      hint: "Required — this wipes every row in the table",
      show: { operation: ["deleteAll"] } },

    { name: "rpcFunction", type: "string", label: "Function Name", smart: true, required: true, placeholder: "my_function",
      show: { operation: ["rpc"] } },
    { name: "rpcParams", type: "string", label: "Parameters", smart: true, multiline: true,
      hint: "JSON object of named arguments",
      show: { operation: ["rpc"] } },

    { name: "accessToken", type: "string", label: "Access Token", smart: true,
      hint: "The user's JWT. Leave blank to use the credential's own session.",
      show: { operation: ["getUser"] } },
    { name: "page", type: "number", label: "Page", default: 1,
      show: { operation: ["listUsers"] } },
    { name: "email", type: "string", label: "Email", smart: true, required: true, placeholder: "{{ $json.email }}",
      show: { operation: ["createUser", "inviteUser"] } },
    { name: "password", type: "string", label: "Password", smart: true,
      show: { operation: ["createUser"] } },
    { name: "emailConfirm", type: "boolean", label: "Mark Email Confirmed", default: false,
      show: { operation: ["createUser"] } },
    { name: "userMetadata", type: "string", label: "User Metadata", smart: true, multiline: true,
      hint: "JSON object stored on the user record",
      show: { operation: ["createUser"] } },
    { name: "userId", type: "string", label: "User ID", smart: true, required: true,
      show: { operation: ["deleteUser"] } },
    { name: "redirectTo", type: "string", label: "Redirect URL", smart: true,
      hint: "Where the invite link lands after acceptance",
      show: { operation: ["inviteUser"] } },

    { name: "bucket", type: "string", label: "Bucket", smart: true, required: true, placeholder: "avatars",
      show: { operation: ["listFiles", "createSignedUrl", "getPublicUrl", "deleteFile"] } },
    { name: "path", type: "string", label: "Path", smart: true, placeholder: "public/logo.png",
      show: { operation: ["listFiles", "createSignedUrl", "getPublicUrl", "deleteFile"] } },
    { name: "expiresIn", type: "number", label: "Expires In (seconds)", default: 3600,
      show: { operation: ["createSignedUrl"] } },
  ],
  outputs: ["rows", "row", "count", "inserted", "updated", "upserted", "deleted", "result", "user", "users", "buckets", "files", "signedUrl", "publicUrl"],
};
