export default {
  backendType: "supabase",
  label: "Supabase",
  description: "Select, insert, update, delete, upsert, and call RPC functions in Supabase.",
  fields: [
    { name: "credentialId", type: "credential", label: "Supabase Credential", accentColor: "#3ECF8E" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "select", options: [
      { value: "select", label: "Select" },
      { value: "insert", label: "Insert" },
      { value: "update", label: "Update" },
      { value: "delete", label: "Delete" },
      { value: "upsert", label: "Upsert" },
      { value: "rpc",    label: "RPC" },
    ]},
    { name: "table", type: "string", label: "Table", smart: true, placeholder: "users",
      show: { operation: ["select","insert","update","delete","upsert"] } },
    { name: "columns", type: "string", label: "Columns", smart: true, default: "*",
      show: { operation: ["select"] } },
    { name: "filter", type: "string", label: "Filter", smart: true,
      hint: "column=value format or leave blank",
      show: { operation: ["select"] } },
    { name: "limit", type: "number", label: "Limit", default: 100,
      show: { operation: ["select"] } },
    { name: "orderBy", type: "string", label: "Order By", smart: true,
      show: { operation: ["select"] } },
    { name: "ascending", type: "boolean", label: "Ascending", default: true,
      show: { operation: ["select"] } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true,
      hint: "JSON object or array of objects",
      show: { operation: ["insert"] } },
    { name: "filter", type: "string", label: "Filter", smart: true,
      hint: "column=value",
      show: { operation: ["update","delete"] } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true,
      hint: "JSON object of columns to update",
      show: { operation: ["update"] } },
    { name: "data", type: "string", label: "Data", smart: true, multiline: true,
      hint: "JSON object or array",
      show: { operation: ["upsert"] } },
    { name: "onConflict", type: "string", label: "On Conflict", smart: true,
      hint: "Column name(s) for conflict resolution",
      show: { operation: ["upsert"] } },
    { name: "functionName", type: "string", label: "Function Name", smart: true, placeholder: "my_function",
      show: { operation: ["rpc"] } },
    { name: "params", type: "string", label: "Parameters", smart: true, multiline: true,
      hint: "JSON object of parameters",
      show: { operation: ["rpc"] } },
  ],
  outputs: ["data","count","error"],
};
