export default {
  backendType: "telegram",
  label: "Telegram",
  description: "Send messages, photos, documents, polls, and manage chats via the Telegram Bot API.",
  fields: [
    { name: "credentialId", label: "Bot Token", type: "credential", accentColor: "#229ED9" },
    { name: "operation", label: "Operation", type: "options", cols: 3, default: "sendMessage", options: [
      { value: "sendMessage",  label: "Send Message" },
      { value: "sendPhoto",    label: "Send Photo" },
      { value: "sendDocument", label: "Send Document" },
      { value: "sendPoll",     label: "Send Poll" },
      { value: "editMessage",  label: "Edit Message" },
      { value: "pinMessage",   label: "Pin Message" },
      { value: "getChat",      label: "Get Chat" },
    ]},
    { name: "chatId", label: "Chat ID", type: "string", smart: true, placeholder: "@username or -1001234567890", show: { operation: ["sendMessage","sendPhoto","sendDocument","sendPoll","editMessage","pinMessage","getChat"] } },
    { name: "text", label: "Text", type: "string", smart: true, multiline: true, show: { operation: ["sendMessage","editMessage"] } },
    { name: "parseMode", label: "Parse Mode", type: "options", cols: 3, default: "HTML", options: [
      { value: "HTML",       label: "HTML" },
      { value: "Markdown",   label: "Markdown" },
      { value: "MarkdownV2", label: "MarkdownV2" },
    ], show: { operation: ["sendMessage","editMessage"] } },
    { name: "photoUrl", label: "Photo URL", type: "string", smart: true, show: { operation: "sendPhoto" } },
    { name: "caption", label: "Caption (optional)", type: "string", smart: true, multiline: true, show: { operation: ["sendPhoto","sendDocument"] } },
    { name: "documentUrl", label: "Document URL", type: "string", smart: true, show: { operation: "sendDocument" } },
    { name: "filename", label: "Filename (optional)", type: "string", smart: true, show: { operation: "sendDocument" } },
    { name: "question", label: "Question", type: "string", smart: true, show: { operation: "sendPoll" } },
    { name: "options", label: "Options", type: "string", smart: true, multiline: true, hint: "One option per line", show: { operation: "sendPoll" } },
    { name: "isAnonymous", label: "Anonymous", type: "boolean", default: true, show: { operation: "sendPoll" } },
    { name: "allowsMultipleAnswers", label: "Allow Multiple Answers", type: "boolean", default: false, show: { operation: "sendPoll" } },
    { name: "messageId", label: "Message ID", type: "string", smart: true, show: { operation: ["editMessage","pinMessage"] } },
  ],
  outputs: ["message", "poll", "chat"],
};
