export default {
  backendType: "google_drive",
  label: "Google Drive",
  description: "List, upload, download, move, delete, and share files in Google Drive.",
  fields: [
    { name: "credentialId", type: "credential", label: "Google Credential", accentColor: "#4285F4" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "listFiles", options: [
      { value: "listFiles",    label: "List Files" },
      { value: "getFile",      label: "Get File" },
      { value: "uploadText",   label: "Upload Text" },
      { value: "downloadText", label: "Download Text" },
      { value: "createFolder", label: "Create Folder" },
      { value: "moveFile",     label: "Move File" },
      { value: "deleteFile",   label: "Delete File" },
      { value: "shareFile",    label: "Share File" },
    ]},
    { name: "folderId", type: "string", label: "Folder ID", smart: true,
      hint: "Leave blank for root",
      show: { operation: ["listFiles"] } },
    { name: "query", type: "string", label: "Query", smart: true, placeholder: "name contains 'report'",
      show: { operation: ["listFiles"] } },
    { name: "limit", type: "number", label: "Limit", default: 50,
      show: { operation: ["listFiles"] } },
    { name: "fileId", type: "string", label: "File ID", smart: true,
      show: { operation: ["getFile","downloadText","moveFile","deleteFile","shareFile"] } },
    { name: "name", type: "string", label: "File Name", smart: true,
      show: { operation: ["uploadText"] } },
    { name: "content", type: "string", label: "Content", smart: true, multiline: true,
      show: { operation: ["uploadText"] } },
    { name: "mimeType", type: "string", label: "MIME Type", smart: true, default: "text/plain",
      show: { operation: ["uploadText"] } },
    { name: "folderId", type: "string", label: "Parent Folder ID", smart: true,
      show: { operation: ["uploadText"] } },
    { name: "name", type: "string", label: "Folder Name", smart: true,
      show: { operation: ["createFolder"] } },
    { name: "parentFolderId", type: "string", label: "Parent Folder ID", smart: true,
      show: { operation: ["createFolder"] } },
    { name: "destinationFolderId", type: "string", label: "Destination Folder ID", smart: true,
      show: { operation: ["moveFile"] } },
    { name: "role", type: "options", label: "Role", cols: 3, default: "reader",
      options: [
        { value: "reader",    label: "Reader" },
        { value: "writer",    label: "Writer" },
        { value: "commenter", label: "Commenter" },
      ],
      show: { operation: ["shareFile"] } },
    { name: "type", type: "options", label: "Type", cols: 3, default: "anyone",
      options: [
        { value: "user",   label: "User" },
        { value: "group",  label: "Group" },
        { value: "anyone", label: "Anyone" },
      ],
      show: { operation: ["shareFile"] } },
    { name: "emailAddress", type: "string", label: "Email Address", smart: true,
      hint: "Required for user/group type",
      show: { operation: ["shareFile"] } },
  ],
  outputs: ["file","files","folder","content","url"],
};
