export default {
  backendType: "mailchimp",
  label: "Mailchimp",
  description: "Manage audiences, subscribers, and campaigns in Mailchimp.",
  fields: [
    { type: "notice", variant: "info", text: "Requires a Mailchimp OAuth credential or API key." },
    { name: "credentialId", label: "Mailchimp Credential", type: "credential", accentColor: "#FFE01B" },
    { name: "operation", label: "Operation", type: "options", cols: 3, default: "listAudiences", options: [
      { value: "listAudiences",     label: "List Audiences" },
      { value: "listSubscribers",   label: "List Subscribers" },
      { value: "addSubscriber",     label: "Add Subscriber" },
      { value: "updateSubscriber",  label: "Update Subscriber" },
      { value: "listCampaigns",     label: "List Campaigns" },
      { value: "getCampaign",       label: "Get Campaign" },
      { value: "sendCampaign",      label: "Send Campaign" },
    ]},
    { name: "audienceId", label: "Audience ID", type: "string", smart: true, show: { operation: ["listSubscribers","addSubscriber","updateSubscriber"] } },
    { name: "status", label: "Status", type: "options", cols: 2, options: [
      { value: "subscribed",   label: "Subscribed" },
      { value: "unsubscribed", label: "Unsubscribed" },
      { value: "pending",      label: "Pending" },
      { value: "cleaned",      label: "Cleaned" },
    ], show: { operation: ["listSubscribers","updateSubscriber"] } },
    { name: "count", label: "Count", type: "number", default: 100, show: { operation: "listSubscribers" } },
    { name: "email", label: "Email", type: "string", smart: true, show: { operation: ["addSubscriber","updateSubscriber"] } },
    { name: "firstName", label: "First Name (optional)", type: "string", smart: true, show: { operation: "addSubscriber" } },
    { name: "lastName", label: "Last Name (optional)", type: "string", smart: true, show: { operation: "addSubscriber" } },
    { name: "addStatus", label: "Status", type: "options", cols: 2, default: "subscribed", options: [
      { value: "subscribed", label: "Subscribed" },
      { value: "pending",    label: "Pending" },
    ], show: { operation: "addSubscriber" } },
    { name: "campaignCount", label: "Count", type: "number", default: 20, show: { operation: "listCampaigns" } },
    { name: "campaignId", label: "Campaign ID", type: "string", smart: true, show: { operation: ["getCampaign","sendCampaign"] } },
  ],
  outputs: ["audiences", "subscribers", "member", "campaigns", "campaign"],
};
