export default {
  backendType: "redis_node",
  label: "Redis",
  description: "Get, set, delete, and work with lists, hashes, sets, and pub/sub in Redis.",
  fields: [
    { name: "credentialId", type: "credential", label: "Redis Credential", accentColor: "#DC382D" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "get", options: [
      { value: "get",       label: "Get" },
      { value: "set",       label: "Set" },
      { value: "del",       label: "Delete" },
      { value: "exists",    label: "Exists" },
      { value: "expire",    label: "Expire" },
      { value: "lpush",     label: "LPush" },
      { value: "rpush",     label: "RPush" },
      { value: "lpop",      label: "LPop" },
      { value: "rpop",      label: "RPop" },
      { value: "lrange",    label: "LRange" },
      { value: "hset",      label: "HSet" },
      { value: "hget",      label: "HGet" },
      { value: "hgetall",   label: "HGetAll" },
      { value: "hdel",      label: "HDel" },
      { value: "sadd",      label: "SAdd" },
      { value: "smembers",  label: "SMembers" },
      { value: "srem",      label: "SRem" },
      { value: "incr",      label: "Incr" },
      { value: "publish",   label: "Publish" },
      { value: "subscribe", label: "Subscribe" },
    ]},
    { name: "key", type: "string", label: "Key", smart: true, placeholder: "user:123",
      show: { operation: ["get","set","del","exists","expire","lpush","rpush","lpop","rpop","lrange","hset","hget","hgetall","hdel","sadd","smembers","srem","incr"] } },
    { name: "value", type: "string", label: "Value", smart: true,
      show: { operation: ["set"] } },
    { name: "ttl", type: "number", label: "TTL (seconds)", hint: "TTL in seconds, 0 = no expiry",
      show: { operation: ["set"] } },
    { name: "ttl", type: "number", label: "TTL (seconds)", hint: "Seconds until expiry",
      show: { operation: ["expire"] } },
    { name: "values", type: "string", label: "Values", smart: true,
      hint: "Comma-separated values to push",
      show: { operation: ["lpush","rpush"] } },
    { name: "start", type: "number", label: "Start", default: 0,
      show: { operation: ["lrange"] } },
    { name: "stop", type: "number", label: "Stop", default: -1,
      show: { operation: ["lrange"] } },
    { name: "field", type: "string", label: "Field", smart: true,
      show: { operation: ["hset","hget","hdel"] } },
    { name: "value", type: "string", label: "Value", smart: true,
      show: { operation: ["hset"] } },
    { name: "members", type: "string", label: "Members", smart: true,
      hint: "Comma-separated",
      show: { operation: ["sadd"] } },
    { name: "members", type: "string", label: "Members", smart: true,
      show: { operation: ["srem"] } },
    { name: "amount", type: "number", label: "Amount", default: 1,
      show: { operation: ["incr"] } },
    { name: "channel", type: "string", label: "Channel", smart: true,
      show: { operation: ["publish","subscribe"] } },
    { name: "message", type: "string", label: "Message", smart: true,
      show: { operation: ["publish"] } },
  ],
  outputs: ["value","values","exists","count","members","hash"],
};
