const KEY_OPS = [
  "get", "set", "setnx", "getset", "append", "del", "exists", "type", "rename",
  "incr", "decr", "expire", "ttl", "persist",
  "lpush", "rpush", "lpop", "rpop", "lrange", "llen",
  "sadd", "srem", "smembers", "sismember", "scard", "zadd", "zrange", "zscore",
  "hset", "hget", "hgetall", "hmset", "hdel", "hexists", "hkeys", "hvals", "hincrby",
];

export default {
  backendType: "redis_node",
  label: "Redis",
  description: "Read and write keys, lists, sets, sorted sets, hashes, and publish messages.",
  fields: [
    { name: "credentialId", type: "credential", label: "Redis Credential", accentColor: "#DC382D" },

    { name: "key", type: "string", label: "Key", smart: true, required: true, placeholder: "user:123",
      show: { operation: KEY_OPS } },
    { name: "newKey", type: "string", label: "New Key", smart: true, required: true, placeholder: "user:456",
      show: { operation: ["rename"] } },
    { name: "pattern", type: "string", label: "Pattern", smart: true, default: "*", placeholder: "user:*",
      hint: "Glob pattern — * matches anything",
      show: { operation: ["keys"] } },
    { name: "keys", type: "string", label: "Keys", smart: true, required: true, placeholder: "user:1,user:2",
      hint: "Comma-separated, or a JSON array",
      show: { operation: ["mget"] } },
    { name: "pairs", type: "string", label: "Key/Value Pairs", smart: true, multiline: true, required: true,
      hint: "JSON object: {\"user:1\": \"alice\", \"user:2\": \"bob\"}",
      show: { operation: ["mset"] } },

    { name: "value", type: "string", label: "Value", smart: true, required: true,
      show: { operation: ["set", "setnx", "getset", "append", "lpush", "rpush", "sismember", "zadd", "zscore"] } },
    { name: "ttl", type: "number", label: "Expires In (seconds)",
      hint: "Leave blank for no expiry",
      show: { operation: ["set"] } },
    { name: "ttl", type: "number", label: "Expires In (seconds)", required: true,
      show: { operation: ["expire"] } },
    { name: "value", type: "number", label: "Amount", default: 1,
      show: { operation: ["incr", "decr"] } },

    { name: "start", type: "number", label: "Start Index", default: 0,
      show: { operation: ["lrange", "zrange"] } },
    { name: "stop", type: "number", label: "Stop Index", default: -1,
      hint: "-1 means the last item",
      show: { operation: ["lrange", "zrange"] } },
    { name: "withScores", type: "boolean", label: "Include Scores", default: false,
      show: { operation: ["zrange"] } },

    { name: "members", type: "string", label: "Members", smart: true, required: true,
      hint: "Comma-separated, or a JSON array",
      show: { operation: ["sadd", "srem"] } },
    { name: "score", type: "number", label: "Score", required: true,
      hint: "Sorted sets order members by this number",
      show: { operation: ["zadd"] } },

    { name: "field", type: "string", label: "Field", smart: true, required: true, placeholder: "email",
      show: { operation: ["hset", "hget", "hdel", "hexists", "hincrby"] } },
    { name: "value", type: "string", label: "Value", smart: true, required: true,
      show: { operation: ["hset"] } },
    { name: "value", type: "number", label: "Amount", default: 1,
      show: { operation: ["hincrby"] } },
    { name: "fields", type: "string", label: "Fields", smart: true, multiline: true, required: true,
      hint: "JSON object: {\"email\": \"a@b.com\", \"plan\": \"pro\"}",
      show: { operation: ["hmset"] } },

    { name: "channel", type: "string", label: "Channel", smart: true, required: true, placeholder: "notifications",
      show: { operation: ["publish"] } },
    { name: "message", type: "string", label: "Message", smart: true, multiline: true,
      show: { operation: ["publish"] } },
  ],
  outputs: ["value", "values", "exists", "count", "members", "hash", "keys", "type", "ttl", "score", "length", "subscribers"],
};
