export default {
  backendType: "s3",
  label: "AWS S3",
  description: "Upload, download, list, and manage objects in Amazon S3 buckets.",
  fields: [
    { name: "credentialId", type: "credential", label: "AWS Credential", accentColor: "#FF9900" },
    { name: "operation", type: "options", label: "Operation", cols: 2, default: "putObject", options: [
      { value: "putObject",            label: "Put Object" },
      { value: "getObject",            label: "Get Object" },
      { value: "deleteObject",         label: "Delete Object" },
      { value: "listObjects",          label: "List Objects" },
      { value: "exists",               label: "Object Exists" },
      { value: "generatePresignedUrl", label: "Presigned URL" },
    ]},
    { name: "bucket", type: "string", label: "Bucket", smart: true, placeholder: "my-bucket" },
    { name: "region", type: "string", label: "Region", smart: false, default: "us-east-1" },
    { name: "key", type: "string", label: "Object Key", smart: true, placeholder: "folder/file.txt",
      show: { operation: ["putObject","getObject","deleteObject","exists","generatePresignedUrl"] } },
    { name: "body", type: "string", label: "Body", smart: true, multiline: true,
      hint: "File content or JSON",
      show: { operation: ["putObject"] } },
    { name: "contentType", type: "string", label: "Content-Type", smart: true, default: "text/plain",
      show: { operation: ["putObject"] } },
    { name: "prefix", type: "string", label: "Prefix", smart: true, placeholder: "folder/",
      show: { operation: ["listObjects"] } },
    { name: "maxKeys", type: "number", label: "Max Keys", default: 100,
      show: { operation: ["listObjects"] } },
    { name: "expiresIn", type: "number", label: "Expires In", default: 3600,
      hint: "Seconds until URL expires",
      show: { operation: ["generatePresignedUrl"] } },
  ],
  outputs: ["object","objects","url","exists","key"],
};
