export default {
  backendType: "whatsapp",
  label: "WhatsApp",
  description: "Send messages, media, locations, templates, and mark messages as read via the WhatsApp Business API.",
  fields: [
    { name: "credentialId", label: "WhatsApp Business API Credential", type: "credential", accentColor: "#25D366" },
    { name: "operation", label: "Operation", type: "options", cols: 3, default: "sendMessage", options: [
      { value: "sendMessage",  label: "Send Message" },
      { value: "sendImage",    label: "Send Image" },
      { value: "sendDocument", label: "Send Document" },
      { value: "sendAudio",    label: "Send Audio" },
      { value: "sendLocation", label: "Send Location" },
      { value: "sendTemplate", label: "Send Template" },
      { value: "markRead",     label: "Mark Read" },
    ]},
    { name: "to", label: "To (phone number)", type: "string", smart: true, placeholder: "15551234567", hint: "Include country code, no + prefix", show: { operation: ["sendMessage","sendImage","sendDocument","sendAudio","sendLocation","sendTemplate"] } },
    { name: "message", label: "Message", type: "string", smart: true, multiline: true, show: { operation: "sendMessage" } },
    { name: "imageUrl", label: "Image URL", type: "string", smart: true, show: { operation: "sendImage" } },
    { name: "caption", label: "Caption (optional)", type: "string", smart: true, show: { operation: ["sendImage","sendDocument"] } },
    { name: "documentUrl", label: "Document URL", type: "string", smart: true, show: { operation: "sendDocument" } },
    { name: "filename", label: "Filename", type: "string", smart: true, show: { operation: "sendDocument" } },
    { name: "audioUrl", label: "Audio URL", type: "string", smart: true, show: { operation: "sendAudio" } },
    { name: "latitude", label: "Latitude", type: "string", smart: true, placeholder: "37.4218", show: { operation: "sendLocation" } },
    { name: "longitude", label: "Longitude", type: "string", smart: true, placeholder: "-122.0840", show: { operation: "sendLocation" } },
    { name: "name", label: "Location Name (optional)", type: "string", smart: true, show: { operation: "sendLocation" } },
    { name: "address", label: "Address (optional)", type: "string", smart: true, show: { operation: "sendLocation" } },
    { name: "templateName", label: "Template Name", type: "string", smart: true, show: { operation: "sendTemplate" } },
    { name: "languageCode", label: "Language Code", type: "string", smart: true, default: "en_US", show: { operation: "sendTemplate" } },
    { name: "components", label: "Components (optional)", type: "string", smart: true, multiline: true, hint: "JSON array of template component objects", show: { operation: "sendTemplate" } },
    { name: "messageId", label: "Message ID", type: "string", smart: true, show: { operation: "markRead" } },
  ],
  outputs: ["result"],
};
